/* content/speaking/part1.js
   FW: answer frameworks. SPK: [topic, question, framework, tense code, sample answer] */
(() => {
const FW={
 ARE:{name:"Answer · Reason · Example",steps:["Trả lời thẳng vào câu hỏi","Nêu lý do","Đưa một ví dụ cụ thể"],pat:["Yes, definitely. / Not really, to be honest.","The main reason is that …","I'd say it's mainly because …","For example, just last week I …","A good example is …"]},
 ARC:{name:"Answer · Reason · Contrast",steps:["Trả lời","Nêu lý do","Thêm mặt trái hoặc ngoại lệ"],pat:["Generally, yes, because …","It really depends on …","That said, …","On the other hand, I'm not a big fan of …","…, but sometimes I …"]},
 FD:{name:"Frequency · Detail · Feeling",steps:["Bao lâu một lần","Làm gì, ở đâu, với ai","Cảm nhận của bạn"],pat:["I … quite often, maybe two or three times a week.","I usually … with …","Every now and then, I …","It helps me relax / It keeps me …","I find it really …"]},
 PC:{name:"Preference · Comparison · Reason",steps:["Chọn một bên","So sánh hai bên","Giải thích vì sao"],pat:["I'd say I prefer X to Y.","X is much more … than Y.","Whereas Y is …, X is …","That's why I'd rather …","It depends, but most of the time I …"]},
 PN:{name:"Past · Now · Why",steps:["Ngày trước thế nào","Bây giờ thế nào","Vì sao thay đổi"],pat:["When I was a kid, I used to …","These days, I … / Now that I'm older, …","It has changed a lot over the past few years.","I guess that's because …","Compared to the past, …"]},
 DF:{name:"Describe · Feature · Feeling",steps:["Mô tả chung","Điểm nổi bật","Cảm nhận"],pat:["It's a … located in …","What stands out is …","It's well known for …","The thing I like most is …","I always feel … there."]},
 ST:{name:"When · What · Feeling",steps:["Khi nào, ở đâu","Chuyện gì đã xảy ra","Cảm nhận hoặc kết quả"],pat:["It was about … ago, when I …","I/We … and then …","It turned out to be …","It was one of the best … I've ever …","Looking back, I …"]},
 FP:{name:"Wish · Reason · Plan",steps:["Mong muốn","Lý do","Kế hoạch cụ thể"],pat:["I'd love to … / I'm thinking of …","mainly because …","I'm planning to … next year.","Hopefully, I'll be able to …","If I have the chance, I will …"]},
};
// [chủ đề, câu hỏi, khung, thì chính, câu trả lời mẫu]
const SPK=[
 ["Work & Study","Do you work or are you a student?","ARE","ps","I'm working as a designer at a tech company. I chose it because I love solving problems visually. For example, this week I'm redesigning a banking app."],
 ["Work & Study","Why did you choose that job or major?","ARE","pas","I chose it mainly because I was good at drawing at school. My teacher also encouraged me. When I tried my first design course, I knew it was right for me."],
 ["Work & Study","What do you like most about your job or studies?","DF","ps","It's a creative job where every project is different. What stands out is the people I work with. I always feel motivated when we share ideas."],
 ["Work & Study","Is there anything you dislike about your job or studies?","ARC","ps","Generally, I enjoy it, but the deadlines can be stressful. That said, the pressure pushes me to work smarter, so it isn't all bad."],
 ["Work & Study","What was your favourite subject at school?","ARE","pas","It was definitely literature. The main reason is that I loved stories. For example, I once spent a whole summer reading Vietnamese classics."],
 ["Work & Study","Would you like to change your job in the future?","FP","fs","Not really, but I'd love to move into a teaching role one day. I enjoy helping beginners, so I'm planning to run some workshops next year."],
 ["Hometown","Where is your hometown?","DF","ps","My hometown is Da Lat, a small city located in the Central Highlands. It's well known for its cool weather and pine forests. I always feel relaxed there."],
 ["Hometown","What do you like most about your hometown?","ARE","ps","I'd say the food. The main reason is that it's cheap and tasty. For example, you can get a delicious bowl of noodles for about thirty thousand dong."],
 ["Hometown","Has your hometown changed much in recent years?","PN","pp","Yes, a lot. When I was a kid, there were only small shops. These days, there are big malls and new roads. I guess that's because more tourists come now."],
 ["Hometown","Is your hometown a good place for young people?","ARC","ps","Yes, in some ways, because there are lots of cafés and events. On the other hand, good jobs are limited, so many young people move to bigger cities."],
 ["Hometown","Would you like to live in your hometown in the future?","FP","fs","I'd love to go back when I'm older, mainly because life there is slower. For now, I'm planning to stay in the city for my career."],
 ["Hometown","What is your hometown famous for?","DF","ps","It's famous for its seafood and beautiful beaches. What stands out is the fresh fish market in the morning. Visitors always say they want to come back."],
 ["Home","Do you live in a house or an apartment?","DF","ps","I live in a small apartment on the tenth floor. The thing I like most is the view of the river. It feels cosy, especially at night."],
 ["Home","What is your favourite room in your home?","ARE","ps","Definitely my bedroom. It's the only place where I can be alone. For example, every evening I read there for half an hour before sleeping."],
 ["Home","How long have you lived there?","PN","ppc","I've been living there for about three years. Before that, I used to share a room with friends. I moved because I needed more quiet space to work."],
 ["Home","What would you change about your home?","FP",null,"I'd love to have a bigger kitchen, mainly because I enjoy cooking. If I have the chance, I will also add more plants to the balcony."],
 ["Home","Do you plan to live there for a long time?","FP","fs","Probably not. I'm thinking of buying a place closer to my office, mainly because the traffic is terrible. Hopefully, I'll be able to move in two years."],
 ["Family","How many people are there in your family?","DF","ps","There are four people in my family: my parents, my younger brother and me. What stands out is how close we are. I always feel supported at home."],
 ["Family","Who are you closest to in your family?","ARE","ps","I'm closest to my mother. The main reason is that she always listens to me. For example, she's the first person I call when I have news."],
 ["Family","Do you often spend time with your family?","FD","ps","Not as often as I'd like, maybe once a week. We usually have dinner together on Sundays. It's the moment I look forward to most."],
 ["Family","What do you usually do together with your family?","FD","ps","We usually cook and eat together at weekends. Every now and then, we go on a short trip to the beach. It keeps us connected."],
 ["Friends","Do you have many friends?","ARC","ps","Not many, but I have a few really close ones. That said, I know quite a lot of people through work. I prefer quality to quantity."],
 ["Friends","How often do you meet your friends?","FD","ps","I meet them about twice a month. We usually grab coffee or try a new restaurant. I find it really refreshing after a busy week."],
 ["Friends","Where did you meet your best friend?","ST","pas","We met about ten years ago at university. We were in the same group project and then started studying together every day. Looking back, I was really lucky."],
 ["Friends","Is it easy to make friends where you live?","ARC","ps","Generally, yes, because people are friendly. That said, everyone is busy in a big city, so it can be hard to keep in touch."],
 ["Free time","What do you do in your free time?","FD","ps","I usually read or go for a walk in the park. Every now and then, I watch a film with friends. It helps me recharge."],
 ["Free time","Do you have a hobby?","ARE","ps","Yes, I love painting. I'd say it's mainly because it calms me down. For example, last weekend I painted the view from my balcony."],
 ["Free time","Did you have the same hobbies as a child?","PN","pas","Not really. When I was a kid, I used to play football every afternoon. Now that I'm older, I prefer quieter hobbies like reading."],
 ["Free time","Is there a hobby you would like to try?","FP","fs","I'd love to try pottery, mainly because it looks so relaxing. I'm planning to join a class near my house next month."],
 ["Free time","Do you prefer spending free time alone or with others?","PC","ps","I'd say I prefer spending time with others. Being alone is peaceful, whereas being with friends is more fun. That's why I usually make plans at weekends."],
 ["Free time","How do you usually spend your weekends?","FD","ps","I usually sleep in on Saturday and meet friends in the afternoon. On Sundays I visit my parents. It's a nice balance."],
 ["Music","What kind of music do you like?","ARE","ps","I'm a big fan of acoustic music. The main reason is that it's relaxing. For example, I always play some guitar songs while I'm working."],
 ["Music","When do you usually listen to music?","FD","ps","I listen to music almost every day, mostly when I commute. I usually put on a playlist on my phone. It makes the traffic less annoying."],
 ["Music","Have you ever learnt to play a musical instrument?","ST","pp","Yes, I learnt the piano when I was about eight. I practised every day for three years, and then I stopped. Looking back, I wish I had continued."],
 ["Music","Do you prefer live music or recorded music?","PC","ps","I'd say I prefer live music. Recorded music is convenient, whereas live music has much more energy. That's why I go to concerts whenever I can."],
 ["Reading","Do you like reading?","ARE","ps","Yes, definitely. It's mainly because books help me escape from daily stress. For example, I'm reading a novel about Japan right now."],
 ["Reading","What kind of books did you read as a child?","PN","pas","When I was a kid, I used to read comics all the time. These days, I read more non-fiction. I guess my interests have become more practical."],
 ["Reading","Do you prefer paper books or e-books?","PC","ps","I prefer paper books to e-books. E-books are lighter, whereas paper books feel more real. That's why I'd rather buy a printed copy."],
 ["Reading","What was the last book you read?","ST","pas","It was a self-help book I read about two weeks ago. It talked about building small habits. It turned out to be really useful for my routine."],
 ["Sports","Do you like sports?","ARE","ps","Yes, I do. The main reason is that sport keeps me healthy. For example, I play badminton with my colleagues every Thursday."],
 ["Sports","How often do you exercise?","FD","ps","I exercise about three times a week. I usually go jogging in the morning before work. It keeps me energetic for the whole day."],
 ["Sports","What sports are popular in your country?","DF","ps","Football is by far the most popular sport in Vietnam. What stands out is how crazy fans get during big matches. The streets are full of people celebrating."],
 ["Sports","Did you play any sports when you were younger?","PN","pas","Yes, I used to play volleyball at school. These days, I don't have time for team sports, so I go swimming instead because it's more flexible."],
 ["Food","What is your favourite food?","ARE","ps","My favourite food is phở. The main reason is that it's warm and full of flavour. For example, I have it for breakfast almost every Sunday."],
 ["Food","Do you like cooking?","ARC","ps","Generally, yes, because it's creative. That said, I don't cook on weekdays since I'm too tired after work. I mostly cook at weekends."],
 ["Food","Do you prefer eating at home or eating out?","PC","ps","I'd say I prefer eating at home. Eating out is convenient, whereas home-cooked food is healthier and cheaper. That's why I usually cook dinner myself."],
 ["Food","Is there any food you didn't like as a child but like now?","PN","pas","Yes, bitter melon. When I was a kid, I used to hate its taste. Now that I'm older, I actually enjoy it, maybe because my taste has changed."],
 ["Food","What is a traditional dish from your country?","DF","ps","A typical dish is bánh chưng, a square rice cake. It's well known as a Tết food. Making it with my family is a special memory."],
 ["Weather","What's the weather like in your hometown?","DF","ps","It's hot and humid most of the year. What stands out is the rainy season, when it pours every afternoon. I've got used to carrying a raincoat."],
 ["Weather","What is your favourite season?","ARE","ps","I love autumn. The main reason is that the air is cool and fresh. For example, in Hanoi people walk around the lake and enjoy the breeze."],
 ["Weather","Does the weather affect your mood?","ARE","ps","Yes, quite a lot. When it's sunny, I feel more productive. For example, on rainy days I often feel lazy and just want to stay in bed."],
 ["Shopping","Do you enjoy shopping?","ARC","ps","It depends. I enjoy shopping for books, but I find clothes shopping tiring. That said, I sometimes go to the mall just to relax."],
 ["Shopping","Do you prefer shopping online or in stores?","PC","ps","I prefer shopping online. Stores are crowded, whereas online shopping saves time. That's why I'd rather order things on my phone."],
 ["Shopping","What was the last thing you bought?","ST","pas","The last thing I bought was a pair of running shoes, about a week ago. I tried them on in the store and then ordered online for a better price."],
 ["Shopping","How often do you go shopping?","FD","ps","I go shopping maybe once a month. I usually buy groceries online, so I only visit stores for special things. I find it more efficient."],
 ["Travel","Do you like travelling?","ARE","ps","Yes, definitely. It's mainly because I love trying new food. For example, last year I went to Hue just to taste the local dishes."],
 ["Travel","Where did you go on your last holiday?","ST","pas","I went to Phu Quoc about three months ago with my family. We swam, ate seafood and watched the sunset. It was one of the best trips I've ever had."],
 ["Travel","Do you prefer travelling alone or with others?","PC","ps","I'd rather travel with friends. Travelling alone gives you freedom, whereas group trips are more fun and safer. That's why I usually go with a group."],
 ["Travel","Where would you like to travel in the future?","FP","fs","I'd love to visit Japan, mainly because of its culture and food. I'm planning to go in spring next year to see the cherry blossoms."],
 ["Transport","How do you usually get to work or school?","FD","ps","I usually ride my motorbike. It takes about twenty minutes. Every now and then, when it rains heavily, I take a ride-hailing car instead."],
 ["Transport","Is public transport good in your city?","ARC","ps","It's getting better because the new metro line has opened. On the other hand, buses are still slow, so most people prefer motorbikes."],
 ["Transport","Do you think people will use cars less in the future?","ARE","fs","Yes, I think so. The main reason is that cities are building more metro lines. For example, my city will open two new lines soon."],
 ["Technology","How often do you use your phone?","FD","ps","Honestly, all the time, maybe six hours a day. I use it for work, music and messages. Sometimes I feel I should take a break."],
 ["Technology","What apps do you use most?","ARE","ps","I'd say messaging apps. It's mainly because I stay in touch with my team. For example, we plan every project in a group chat."],
 ["Technology","Could you live without your mobile phone?","ARC","ps","Probably not, because I need it for work. That said, I'd like to try a phone-free weekend to see how it feels."],
 ["Technology","How has technology changed the way you study or work?","PN","pp","It has changed a lot. When I was a student, I used to go to the library. These days, I can find everything online in seconds."],
 ["Internet","Do you use social media much?","ARC","ps","Yes, quite a lot, because it helps me follow the news. On the other hand, it can be a waste of time, so I try to limit it."],
 ["Internet","What do you usually do online?","FD","ps","I usually read articles and watch tutorials. Every now and then, I shop online. I find the internet really useful for learning."],
 ["Internet","Do you think young people spend too much time online?","ARC","ps","Generally, yes, because many teenagers are always on their phones. That said, they also use the internet to learn new skills."],
 ["Daily routine","What do you usually do in the morning?","FD","ps","I usually wake up at six and make coffee. Then I check my emails and get ready for work. It helps me start the day calmly."],
 ["Daily routine","Are you a morning person or a night person?","PC","ps","I'd say I'm a morning person. Evenings are relaxing, whereas mornings are when my mind is clearest. That's why I do my hardest tasks early."],
 ["Daily routine","Has your daily routine changed recently?","PN","pp","Yes, it has. I used to work late at night, but now I go to bed earlier. I changed because I wanted more energy in the morning."],
 ["Daily routine","What is the busiest part of your day?","ARE","ps","Definitely the morning. The main reason is that most meetings happen then. For example, yesterday I had four meetings before lunch."],
 ["Sleep","How many hours do you usually sleep?","FD","ps","I usually sleep about seven hours. On weekends, I sometimes sleep a bit longer. I always feel better when I get enough rest."],
 ["Sleep","Do you ever take naps during the day?","FD","ps","Yes, I often take a short nap after lunch, maybe fifteen minutes. It's very common in Vietnam. It keeps me focused in the afternoon."],
 ["Clothes","What kind of clothes do you usually wear?","DF","ps","I usually wear simple, comfortable clothes like T-shirts and jeans. What stands out is that I mostly choose neutral colours. They're easy to match."],
 ["Clothes","Do you care about fashion?","ARC","ps","Not really, because I prefer comfort to style. That said, I do dress up for special events like weddings."],
 ["Clothes","Did you wear a uniform at school?","PN","pas","Yes, I did. When I was in high school, I used to wear a white shirt every day. Now I miss it because I didn't have to choose clothes."],
 ["Movies","What kind of films do you like?","ARE","ps","I love animated films. It's mainly because they're creative and heart-warming. For example, I've watched every Studio Ghibli film."],
 ["Movies","Do you prefer watching films at home or at the cinema?","PC","ps","I prefer the cinema to home. Watching at home is cheaper, whereas the cinema has a much better screen and sound. That's why I go there for big releases."],
 ["Movies","What was the last film you watched?","ST","pas","The last film I watched was a Vietnamese comedy, last Saturday. I went with my friends and we laughed the whole time. It turned out to be really fun."],
 ["Festivals","What is the most important festival in your country?","DF","ps","The most important festival is Tết, the Lunar New Year. It's well known for family reunions. I always feel warm and happy during that time."],
 ["Festivals","How do you usually celebrate Tết?","FD","ps","I usually go back to my hometown. We clean the house, cook special food and visit relatives. It's the time I feel closest to my family."],
 ["Festivals","How did you celebrate your last birthday?","ST","pas","On my last birthday, about two months ago, my friends threw a small party for me. We had dinner and then sang karaoke. It was a lovely surprise."],
 ["English","How long have you been learning English?","PN","ppc","I've been learning English for about ten years. At first, I used to study only grammar. These days, I focus more on speaking and listening."],
 ["English","What is the most difficult part of learning English?","ARE","ps","For me, it's speaking. The main reason is that I don't practise enough. For example, I sometimes freeze when I talk to native speakers."],
 ["English","Would you like to learn another language?","FP","fs","I'd love to learn Japanese, mainly because I enjoy Japanese films. I'm planning to take an online course next year."],
 ["Neighbourhood","Do you know your neighbours well?","ARC","ps","Not very well, because everyone is busy. That said, we always say hello in the lift and sometimes share food during Tết."],
 ["Neighbourhood","What is your neighbourhood like?","DF","ps","It's a busy area with lots of street food stalls. What stands out is the small park nearby. I feel lucky to have some green space."],
 ["Neighbourhood","What would you like to improve in your neighbourhood?","FP",null,"I'd love to have more trees, mainly because it's very hot in summer. If I have the chance, I will join a tree-planting project."],
 ["Nature","Do you often go to parks?","FD","ps","Yes, I go to the park near my house about three times a week. I usually jog or just sit and read. It helps me clear my mind."],
 ["Nature","Do you prefer the countryside or the city?","PC","ps","I prefer the city for now. The countryside is peaceful, whereas the city has more opportunities. That's why I'd rather live in the city while I'm young."],
 ["Photos","Do you like taking photos?","ARE","ps","Yes, I do. The main reason is that photos help me remember moments. For example, I take a photo of every meal when I travel."],
 ["Photos","What do you do with the photos you take?","FD","ps","I usually keep them in my phone. Every now and then, I print some and put them on my wall. I find it nice to see them every day."],
 ["Others","Have you ever received a gift you really liked?","ST","pp","Yes, my sister gave me a handmade notebook about a year ago. She drew little pictures on every page. It's one of the best gifts I've ever received."],
 ["Others","Do you like to keep things tidy?","ARC","ps","Generally, yes, because a tidy room helps me focus. That said, my desk gets messy when I'm busy with a project."],
 ["Others","Do you prefer handwriting or typing?","PC","ps","I prefer typing to handwriting. Handwriting is more personal, whereas typing is much faster. That's why I type most of my notes."],
 ["Others","Do you wear a watch?","ARE","ps","Not anymore. The main reason is that I check the time on my phone. For example, my old watch has been in a drawer for years."],
 ["Others","What do you usually do when you feel stressed?","FD","ps","I usually go for a walk or listen to music. Every now and then, I call a friend to talk. It helps me calm down quickly."],
 ["Others","What did you do last weekend?","ST","pas","Last weekend I visited my grandparents in the countryside. We cooked lunch together and then I helped in the garden. It was really peaceful."],
];


GRAMMAR.speaking = { FW, SPK };
})();
