/* content/quiz/emphasis.js: practice questions and game for this module.
   mcQ(type, prompt, hint, right, [wrong…], lessonId, explanation)
   inQ(type, prompt, hint, [accepted answers], lessonId, explanation) */
(() => {
// ---- Emphasis practice (40) ----
const EMPOOL=[];
mcr(EMPOOL,"inv","Chọn câu đảo ngữ đúng.","Viết lại bằng đảo ngữ",[
 ["I have never seen such a beautiful view.","Never have I seen such a beautiful view.",["Never I have seen such a beautiful view.","Never did I have seen such a beautiful view.","Never have seen I such a beautiful view."],"em-neg-inversion","Never + have + S + V3."],
 ["We rarely go out at weekends.","Rarely do we go out at weekends.",["Rarely we go out at weekends.","Rarely we do go out at weekends.","Rarely go we out at weekends."],"em-neg-inversion","Rarely + do + S + V."],
 ["He didn't know the truth at all.","Little did he know the truth.",["Little he knew the truth.","Little did he knew the truth.","Little knew he the truth."],"em-neg-inversion","Little + did + S + V nguyên mẫu."],
 ["She sings and she also dances.","Not only does she sing, but she also dances.",["Not only she sings, but she also dances.","Not only does she sings, but she also dances.","Not only sings she, but she also dances."],"em-not-only","Not only + does + S + V."],
 ["I understood only when she explained.","Only when she explained did I understand.",["Only when did she explain I understood.","Only when she explained I understood.","Only when she explained I did understand."],"em-only","Đảo ngữ ở vế chính."],
 ["He came home at midnight, not before.","Not until midnight did he come home.",["Not until midnight he came home.","Not until midnight did he came home.","Not until midnight came he home."],"em-only","Not until + mốc + did + S + V."],
 ["As soon as I arrived, it started to rain.","No sooner had I arrived than it started to rain.",["No sooner had I arrived when it started to rain.","No sooner I had arrived than it started to rain.","No sooner did I arrive than it had started to rain."],"em-no-sooner","No sooner had S V3 than."],
 ["We had just sat down when the lights went out.","Hardly had we sat down when the lights went out.",["Hardly had we sat down than the lights went out.","Hardly we had sat down when the lights went out.","Hardly did we sit down when the lights went out."],"em-no-sooner","Hardly had S V3 when."],
 ["The film was so boring that I fell asleep.","So boring was the film that I fell asleep.",["So boring the film was that I fell asleep.","So was boring the film that I fell asleep.","So boring did the film that I fell asleep."],"em-so-such","So + adj + be + S."],
 ["We can solve this only by working together.","Only by working together can we solve this.",["Only by working together we can solve this.","Only by working together we solve can this.","Only by work together can we solve this."],"em-only","Only by + V-ing + can + S + V."]]);
mcr(EMPOOL,"cleft","Chọn câu nhấn mạnh đúng.","Nhấn mạnh phần viết hoa",[
 ["LAN broke the vase.","It was Lan who broke the vase.",["It was Lan that she broke the vase.","It is Lan broke the vase.","Lan was who broke the vase."],"em-it-cleft","It was + người + who + V."],
 ["I need A HOLIDAY.","What I need is a holiday.",["What I need it is a holiday.","That I need is a holiday.","What do I need is a holiday."],"em-what-cleft","What + S + V + is."],
 ["I moved here IN 2020.","It was in 2020 that I moved here.",["It was 2020 when I moved here in.","In 2020 was that I moved here.","It is in 2020 that I had moved here."],"em-it-cleft","It was + thời gian + that."],
 ["EDUCATION changes lives.","It is education that changes lives.",["It is education changes lives.","Education is it that changes lives.","It is education what changes lives."],"em-it-cleft","It is + N + that + V."],
 ["I only want SOME SLEEP.","All I want is some sleep.",["All I want it is some sleep.","All what I want is some sleep.","All I want are some sleep."],"em-what-cleft","All + S + V + is."],
 ["I like your idea. (nhấn mạnh)","I do like your idea.",["I do liked your idea.","I does like your idea.","I am like your idea."],"em-do","do + V nguyên mẫu."],
 ["She called you. (khẳng định mạnh)","She did call you.",["She did called you.","She does called you.","She did calls you."],"em-do","did + V nguyên mẫu."],
 ["The government should act. (nhấn mạnh chủ thể)","It is the government that should act.",["It is the government should act.","It is the government who it should act.","The government is that should act."],"em-it-cleft","It is + N + that."],
 ["I love its peaceful pace about Hue.","What I love about Hue is its peaceful pace.",["What I love about Hue it is its peaceful pace.","That I love about Hue is its peaceful pace.","What do I love about Hue is its peaceful pace."],"em-what-cleft","What + S + V + is."],
 ["I left because of THE SALARY.","It was the salary that made me leave.",["It was the salary made me leave.","It was the salary what made me leave.","The salary was it that made me leave."],"em-it-cleft","It was + N + that."]]);
[["Never ___ I seen such a mess.","have"],["Not only ___ she sing, but she also dances.","does"],["Only when he left ___ I realise the truth.","did"],["No sooner ___ we arrived than the show began.","had"],["Little ___ he know what was coming.","did"],["Rarely ___ we eat out these days.","do"],["Hardly ___ I sat down when the phone rang.","had"],["Not until midnight ___ she come home.","did"],["So difficult ___ the test that nobody passed.","was"],["Such ___ the noise that we couldn't sleep.","was"]]
 .forEach(([s,a])=>EMPOOL.push(inQ("aux",fmt(s),"Gõ trợ động từ còn thiếu.",[a],/So |Such /.test(s)?"em-so-such":/sooner|Hardly/.test(s)?"em-no-sooner":/Not only/.test(s)?"em-not-only":/Only|Not until/.test(s)?"em-only":"em-neg-inversion",`Trợ động từ đúng là ${a}.`)));
mcs(EMPOOL,"spot","Chọn câu đúng ngữ pháp.",[
 ["Chọn câu đúng: ___","Never have I been so tired.",["Never I have been so tired.","Never I had been so tired.","Never been have I so tired."],"em-neg-inversion","Never + have + S + V3."],
 ["Chọn câu đúng: ___","It was Nam who called.",["It was Nam who he called.","It was Nam called.","Nam was who called it."],"em-it-cleft","Không lặp chủ ngữ."],
 ["Chọn câu đúng: ___","Not only is it cheap, but it is also fast.",["Not only it is cheap, but it is also fast.","Not only is it cheap, but also it fast.","Not only cheap is it, but also fast."],"em-not-only","Not only + be + S."],
 ["Chọn câu đúng: ___","Seldom does he complain.",["Seldom he complains.","Seldom does he complains.","Seldom complains he."],"em-neg-inversion","Seldom + does + S + V."],
 ["Chọn câu đúng: ___","What surprised me was the price.",["What surprised me it was the price.","What did surprise me was the price.","That surprised me was the price."],"em-what-cleft","What + V + was."],
 ["Chọn câu đúng: ___","Only after the meeting did I understand.",["Only after the meeting I understood.","Only after the meeting I did understand.","Only after did the meeting I understand."],"em-only","Only after + N + did + S + V."],
 ["Chọn câu đúng: ___","No sooner had she left than he arrived.",["No sooner she had left than he arrived.","No sooner had she left when he arrived.","No sooner did she leave when he arrived."],"em-no-sooner","No sooner … than."],
 ["Chọn câu đúng: ___","I do miss my hometown.",["I do missed my hometown.","I does miss my hometown.","I am miss my hometown."],"em-do","do + V."],
 ["Chọn câu đúng: ___","Such was his anger that he left.",["Such his anger was that he left.","So was his anger that he left.","Such anger he was that he left."],"em-so-such","Such + be + N."],
 ["Chọn câu đúng: ___","At no time did she complain.",["At no time she complained.","At no time did she complained.","At no time complained she."],"em-neg-inversion","At no time + did + S + V."]]);
const EMTYPES={inv:{name:"Viết lại bằng đảo ngữ",desc:"Never, Not only, Only when, No sooner, So…"},cleft:{name:"Câu chẻ",desc:"It is … that, What … is, do nhấn mạnh"},aux:{name:"Điền trợ động từ",desc:"Tự gõ do, does, did, have, had, was"},spot:{name:"Chọn câu đúng",desc:"Nhận ra câu nhấn mạnh viết đúng"}};
const EMRUSH=[["Never before ___ I seen this.",["have"]],["Rarely ___ she cook at home.",["does"]],["Little ___ they know.",["did"]],["Not only ___ he rich, but he's kind.",["is"]],["Only then ___ I understand.",["did"]],["No sooner ___ I sat down than…",["had"]],["Hardly ___ we started when…",["had"]],["So tired ___ I that I slept.",["was"]],["Such ___ the crowd that…",["was"]],["Not until 2010 ___ they meet.",["did"]],["Seldom ___ we see snow here.",["do"]],["Never ___ I forget that day.",["will"]],["Only by practising ___ you improve.",["can"]],["At no time ___ he apologise.",["did"]],["Not only ___ they won, but…",["have"]],["Under no circumstances ___ you open it.",["should"]],["Never ___ she been so happy.",["has"]],["Rarely ___ he late for work.",["is"]],["Little ___ she realise.",["did"]],["So difficult ___ the exam that…",["was"]]];

GRAMMAR.quiz["emphasis"] = { pool: EMPOOL, types: EMTYPES, game: {title:"Đảo trợ động từ",desc:"60 giây. Chọn đúng trợ động từ cho câu đảo ngữ",prompt:"Trợ động từ nào?",sentence:true,items:EMRUSH,all:["do","does","did","have","has","had","is","was","will","can","should"],label:c=>`<span class="tl-vi mono">${c}</span>`,name:c=>c,bestKey:"emrushBest"} };
})();
