/* content/theory/emphasis.js: lesson data for this module (edit freely) */
(() => {
const EMV=[
 R_("em-it-cleft","01","It-cleft","Câu chẻ It is … that","It is / was + X + that",
  "Đưa phần muốn nhấn mạnh vào giữa <strong>It is / was … that / who</strong>.",
  [["S","It is / was + người + who + V","<mark>It was Lan who</mark> broke the vase."],["O","It is / was + vật + that + S + V","<mark>It is education that</mark> changes lives."],["adv","It is / was + thời gian, nơi chốn + that …","<mark>It was in 2020 that</mark> I moved here."]],
  [["Sửa thông tin khi nói","No, <mark>it was Nam who</mark> called, not me."],["Nhấn ý chính trong Task 2","<mark>It is the government that</mark> should take action."]],
  ["It is … that","It was … who"],4,4,"Hữu ích cả khi nói và viết để làm rõ trọng tâm.",
  ["It was Lan that she broke the vase.","It was Lan who broke the vase.","Không lặp lại chủ ngữ sau who / that."],
  X_("Thường","Nhấn mạnh","{1:Lan} {2:broke the vase}.","It was {1:Lan} who {2:broke the vase}.")),
 R_("em-what-cleft","02","What-cleft","Câu chẻ What … is","What + S + V + is",
  "Bắt đầu bằng <strong>What + S + V</strong> để tạo sự chờ đợi, rồi nói thông tin chính sau is / was.",
  [["what","What + S + V + is / was + N / to V","<mark>What I need is</mark> a holiday."],["all","All + S + V + is …","<mark>All I want is</mark> some sleep."],["thing","The thing / reason (why) + S + V + is …","<mark>The reason why</mark> I left <mark>is</mark> simple."]],
  [["Speaking: trả lời có chiều sâu","<mark>What I love about Hue is</mark> its peaceful pace."],["Task 2: nêu giải pháp","<mark>What governments should do is</mark> invest in schools."]],
  ["What I …","All I …","The reason why"],5,4,"Rất tự nhiên trong Speaking, giúp trả lời dài và mạch lạc hơn.",
  ["What I need it is a holiday.","What I need is a holiday.","Không thêm it sau What-clause."],
  X_("Thường","Nhấn mạnh","{1:I need} {2:a holiday}.","What {1:I need} is {2:a holiday}.")),
 R_("em-neg-inversion","03","Negative inversion","Đảo ngữ với trạng từ phủ định","Never · Rarely · Little + aux + S",
  "Đưa trạng từ phủ định lên đầu câu, rồi <strong>đảo trợ động từ lên trước chủ ngữ</strong> như câu hỏi.",
  [["never","Never / Rarely / Seldom + aux + S + V","<mark>Never have I</mark> seen such a view."],["little","Little + did + S + V (không hề biết)","<mark>Little did he know</mark> the truth."],["no","At no time / In no way + aux + S + V","<mark>At no time did</mark> she complain."]],
  [["Văn viết trang trọng","<mark>Rarely do</mark> governments admit their mistakes."],["Kể chuyện ấn tượng","<mark>Never before had I</mark> felt so nervous."]],
  ["Never","Rarely","Seldom","Little","At no time"],1,4,"Dùng một lần trong bài viết là đủ để thể hiện cấu trúc khó. Dùng quá nhiều nghe gượng.",
  ["Never I have seen such a view.","Never have I seen such a view.","Sau trạng từ phủ định phải đảo trợ động từ."],
  X_("Thường","Đảo ngữ","{1:I} {2:have} never {3:seen} such a view.","Never {2:have} {1:I} {3:seen} such a view.")),
 R_("em-not-only","04","Not only … but also","Không những … mà còn","Not only + aux + S + V",
  "Khi Not only đứng đầu câu, <strong>vế đầu phải đảo ngữ</strong>; vế sau dùng but (S) also.",
  [["inv","Not only + aux + S + V, but + S + also + V","<mark>Not only does she</mark> sing, but she also dances."],["mid","S + not only + V + but also + V (không đảo)","She <mark>not only</mark> sings <mark>but also</mark> dances."]],
  [["Task 2: thêm luận điểm","<mark>Not only does</mark> exercise improve health, but it also reduces stress."]],
  ["Not only … but also"],2,5,"Cấu trúc kinh điển để thể hiện độ phức tạp của câu.",
  ["Not only she sings, but she also dances.","Not only does she sing, but she also dances.","Not only đứng đầu thì phải đảo ngữ."],
  X_("Thường","Đảo ngữ","{1:She} {2:speaks} English and also French.","Not only {3:does} {1:she} {2:speak} English, but she also speaks French.")),
 R_("em-only","05","Only when / Not until","Only when, Not until","Only when … + aux + S",
  "Only when, Only after, Only by, Not until… đứng đầu thì <strong>đảo ngữ ở vế chính</strong> (vế sau).",
  [["when","Only when + S + V, aux + S + V","<mark>Only when</mark> she explained <mark>did I</mark> understand."],["by","Only by + V-ing + aux + S + V","<mark>Only by</mark> working together <mark>can we</mark> solve this."],["until","Not until + mốc / S + V + aux + S + V","<mark>Not until</mark> midnight <mark>did</mark> he come home."]],
  [["Task 2: nhấn mạnh điều kiện","<mark>Only by</mark> investing in education <mark>can</mark> a country grow."]],
  ["Only when","Only after","Only by","Not until"],1,4,"Rất được ưa chuộng trong bài viết học thuật.",
  ["Only when she explained I understood.","Only when she explained did I understand.","Đảo ngữ ở vế chính, không phải vế Only when."],
  X_("Thường","Đảo ngữ","{1:I} {2:understood} it only when {3:she explained}.","Only when {3:she explained} did {1:I} understand it.")),
 R_("em-no-sooner","06","No sooner / Hardly","Vừa mới … thì","No sooner had S V3 than",
  "Diễn tả hai việc <strong>xảy ra liên tiếp</strong> trong quá khứ. Vế đầu đảo ngữ với had + V3.",
  [["than","No sooner + had + S + V3 + than + S + V2","<mark>No sooner had I</mark> arrived <mark>than</mark> it rained."],["when","Hardly / Scarcely + had + S + V3 + when + S + V2","<mark>Hardly had we</mark> sat down <mark>when</mark> the lights went out."]],
  [["Kể chuyện kịch tính","<mark>No sooner had</mark> the match started <mark>than</mark> it began to rain."]],
  ["No sooner … than","Hardly … when","Scarcely … when"],1,3,"Hay xuất hiện trong bài tập viết lại câu và văn kể chuyện.",
  ["No sooner had I arrived when it rained.","No sooner had I arrived than it rained.","No sooner đi với than; Hardly đi với when."],
  X_("Thường","Đảo ngữ","{1:As soon as I arrived}, {2:it started to rain}.","No sooner {1:had I arrived} than {2:it started to rain}.")),
 R_("em-so-such","07","So / Such inversion","Đảo ngữ với So, Such","So + adj + be + S",
  "Đưa so + tính từ hoặc such lên đầu để <strong>nhấn mạnh mức độ</strong>, rồi đảo be lên trước chủ ngữ.",
  [["so","So + adj + be + S + that …","<mark>So boring was</mark> the film that I fell asleep."],["such","Such + be + N + that …","<mark>Such was</mark> the noise that nobody could sleep."]],
  [["Văn viết miêu tả","<mark>So severe was</mark> the storm that schools closed."]],
  ["So … that","Such … that"],1,3,"Trang trọng, hợp văn viết. Khi nói dùng dạng thường: The film was so boring that…",
  ["So boring the film was that I slept.","So boring was the film that I slept.","Sau So + adj phải đảo be lên trước chủ ngữ."],
  X_("Thường","Đảo ngữ","{1:The film} was {2:so boring} that I fell asleep.","{2:So boring} was {1:the film} that I fell asleep.")),
 R_("em-do","08","Emphatic do","Nhấn mạnh bằng do / does / did","do / does / did + V",
  "Thêm do, does, did trước động từ để <strong>khẳng định mạnh</strong> hoặc phản bác.",
  [["now","S + do / does + V","I <mark>do like</mark> your idea."],["past","S + did + V","She <mark>did call</mark> you, I promise!"]],
  [["Phản bác nhẹ nhàng khi nói","I <mark>do</mark> understand your point, but…"],["Speaking: thể hiện cảm xúc","I <mark>do</mark> miss my hometown."]],
  ["do","does","did"],5,2,"Rất tự nhiên trong Speaking, giúp câu trả lời có cảm xúc.",
  ["She did called you.","She did call you.","Sau did dùng động từ nguyên mẫu."],
  X_("Thường","Nhấn mạnh","I {1:like} your idea.","I {2:do} {1:like} your idea.")),
];



registerRows("emphasis", EMV);
GRAMMAR.theory["emphasis"] = { rows: EMV, first: "em-it-cleft" };
})();
