/* content/theory/passive.js: lesson data for this module (edit freely) */
(() => {
const PV=[
 {id:"p-basic",num:"01",en:"Active → Passive",vi:"Quy tắc chuyển sang bị động",short:"O → S · be + V3 · by + S",
  core:"Câu bị động đưa <strong>đối tượng chịu tác động</strong> lên làm chủ ngữ. Dùng khi người làm không quan trọng, không biết, hoặc muốn nhấn mạnh kết quả.",
  forms:[["1","Tân ngữ chủ động → chủ ngữ bị động","They build <mark>houses</mark>. → <mark>Houses</mark> …"],["2","be (chia theo thì gốc) + V3/ed","… <mark>are built</mark> …"],["3","Chủ ngữ chủ động → by + O (thường bỏ)","… (<mark>by them</mark>)."]],
  uses:[["Không biết ai làm","My bike <mark>was stolen</mark> last night."],["Người làm hiển nhiên hoặc không quan trọng","Rice <mark>is grown</mark> in the Mekong Delta."],["Văn khoa học, báo cáo, tin tức","The samples <mark>were analysed</mark> in the lab."],["Nhấn mạnh kết quả, sản phẩm","This bridge <mark>was built</mark> in 1990."]],
  signals:["by + người làm","be + V3","bỏ by them / by people / by someone"],tenses:[],
  speak:3,write:5,reg:"Văn viết học thuật, báo chí, quy trình dùng rất nhiều. Khi nói, người bản xứ thường dùng chủ động với you, they, people cho tự nhiên.",
  mistake:["The house was build in 2010.","The house was built in 2010.","Sau be luôn là V3 (quá khứ phân từ)."],
  xf:{la:"Chủ động",lb:"Bị động",a:"{1:They} {2:build} {3:houses}.",b:"{3:Houses} {2:are built} ({1:by them}).",note:"Tân ngữ (3) lên đầu câu, động từ (2) thành be + V3, chủ ngữ cũ (1) thành by + O hoặc bỏ đi."}},
 {id:"p-tenses",num:"02",en:"Passive in every tense",vi:"Bị động theo từng thì",short:"be chia theo thì + V3",
  core:"Thì của câu bị động <strong>giữ nguyên thì của câu chủ động</strong>. Chỉ cần chia be theo thì đó rồi thêm V3.",
  forms:[["HTĐ","am / is / are + V3","English <mark>is spoken</mark> here."],["HTTD","am / is / are being + V3","The road <mark>is being repaired</mark>."],["HTHT","have / has been + V3","The tickets <mark>have been sold</mark>."],["QKĐ","was / were + V3","The letter <mark>was sent</mark> yesterday."],["QKTD","was / were being + V3","The car <mark>was being washed</mark>."],["QKHT","had been + V3","The work <mark>had been done</mark> before noon."],["TLĐ","will be + V3","The results <mark>will be announced</mark>."],["TLHT","will have been + V3","It <mark>will have been finished</mark> by May."]],
  uses:[["Thì tiếp diễn bị động: thêm being","They are painting the room. → The room <mark>is being painted</mark>."],["Thì hoàn thành bị động: thêm been","Someone has cleaned it. → It <mark>has been cleaned</mark>."],["Các thì hoàn thành tiếp diễn rất hiếm dùng ở bị động","Thay bằng thì hoàn thành: It <mark>has been built</mark> for years."]],
  signals:["being (tiếp diễn)","been (hoàn thành)","will be","had been"],tensesLabel:"Thì gốc",tenses:[["HTĐ","ps"],["HTTD","pc"],["HTHT","pp"],["QKĐ","pas"],["QKTD","pac"],["QKHT","pap"],["TLĐ","fs"],["TLHT","fp"]],
  speak:3,write:5,reg:"Hiện tại đơn và quá khứ đơn bị động gặp nhiều nhất. Các dạng có being, been hay gặp trong bản tin và báo cáo tiến độ.",
  mistake:["The road is being repair.","The road is being repaired.","Dù có being hay been, động từ chính vẫn là V3."],
  xf:{la:"Chủ động",lb:"Bị động",a:"{1:They} {2:are painting} {3:the house}.",b:"{3:The house} {2:is being painted}.",note:"Thì hiện tại tiếp diễn giữ nguyên: are painting → is being painted."}},
 {id:"p-questions",num:"03",en:"Negatives & questions",vi:"Phủ định và câu hỏi bị động",short:"be + not + V3 · Be + S + V3?",
  core:"Câu phủ định và câu hỏi bị động <strong>dùng chính be</strong> làm trợ động từ, không dùng do, does, did.",
  forms:[["−","S + be + not + V3","The letter <mark>wasn't sent</mark>."],["?","Be + S + V3?","<mark>Was</mark> the letter <mark>sent</mark>?"],["Wh","Wh + be + S + V3?","When <mark>was</mark> the bridge <mark>built</mark>?"],["Who","Who + be + S + V3 + by?","Who <mark>was</mark> this book <mark>written by</mark>?"]],
  uses:[["Hỏi về đối tượng, không quan tâm ai làm","<mark>Has</mark> the room <mark>been cleaned</mark>?"],["Hỏi người làm","Who <mark>was</mark> the Mona Lisa <mark>painted by</mark>?"]],
  signals:["Was … V3?","Has … been V3?","Who … by?"],tenses:[],
  speak:3,write:4,reg:"Câu hỏi bị động hay gặp trong hướng dẫn, khảo sát và email công việc: “Has the invoice been paid?”",
  mistake:["Did the letter sent?","Was the letter sent?","Bị động không dùng did, đảo be lên đầu."],
  xf:{la:"Chủ động",lb:"Bị động",a:"Did {1:they} {2:invite} {3:you}?",b:"Were {3:you} {2:invited}?",note:"did biến mất, thay bằng was/were đứng đầu câu."}},
 {id:"p-two-objects",num:"04",en:"Verbs with two objects",vi:"Động từ có hai tân ngữ",short:"give, send, show, offer…",
  core:"Các động từ như give, send, show, offer, tell, teach có <strong>hai tân ngữ</strong> (người và vật), nên có hai cách viết bị động.",
  forms:[["1","Người làm chủ ngữ (tự nhiên hơn)","<mark>I was given</mark> a gift."],["2","Vật làm chủ ngữ + to / for + người","<mark>A gift was given</mark> to me."]],
  uses:[["Nhấn mạnh người nhận","<mark>She was offered</mark> a job in Singapore."],["Nhấn mạnh vật được trao","<mark>The prize was given</mark> to the youngest student."]],
  signals:["give","send","show","offer","tell","teach","lend"],tenses:[],
  speak:3,write:4,reg:"Cách 1 (người làm chủ ngữ) tự nhiên hơn khi nói. Cách 2 hay gặp trong văn viết trang trọng.",
  mistake:["A gift was given me.","A gift was given to me.","Khi vật làm chủ ngữ, cần thêm to hoặc for trước người."],
  xf:{la:"Chủ động",lb:"Bị động",a:"{1:They} {2:gave} {3:me} {4:a gift}.",b:"{3:I} {2:was given} {4:a gift}.",note:"Cũng có thể viết: A gift was given to me."}},
 {id:"p-modal",num:"05",en:"Modal passive",vi:"Bị động với modal verb",short:"modal + be + V3",
  core:"Với can, must, should, may… chỉ cần <strong>giữ modal, thêm be + V3</strong>.",
  forms:[["M","modal + be + V3","The work <mark>must be finished</mark> today."],["M+","modal + have been + V3","The letter <mark>should have been sent</mark> yesterday."]],
  uses:[["Nội quy, biển báo","Phones <mark>must be switched off</mark>."],["Khả năng, gợi ý","The problem <mark>can be solved</mark> easily."],["Trách móc về quá khứ","This <mark>should have been done</mark> earlier."]],
  signals:["must be","can be","should be","should have been"],tenses:[],
  speak:3,write:5,reg:"Rất phổ biến trong nội quy, hướng dẫn, văn bản công việc.",
  mistake:["The form must be fill in.","The form must be filled in.","Sau modal + be là V3."],
  xf:{la:"Chủ động",lb:"Bị động",a:"{1:You} {2:must finish} {3:the work}.",b:"{3:The work} {2:must be finished}."}},
 {id:"p-reporting",num:"06",en:"It is said that…",vi:"Bị động với động từ tường thuật",short:"It is said that · S is said to V",
  core:"Với say, think, believe, know, report… có <strong>hai cấu trúc</strong> giúp nói về ý kiến chung một cách khách quan.",
  forms:[["1","It + be + V3 + that + mệnh đề","<mark>It is said that</mark> he is rich."],["2","S + be + V3 + to V","He <mark>is said to be</mark> rich."],["3","S + be + V3 + to have V3 (việc trước đó)","He <mark>is said to have been</mark> rich."]],
  uses:[["Tin tức, báo chí","The fire <mark>is believed to have started</mark> in the kitchen."],["Bài viết học thuật","<mark>It is widely thought that</mark> exercise improves memory."]],
  signals:["It is said","is believed to","is thought to","is reported to"],tenses:[],
  speak:1,write:5,reg:"Gần như chỉ dùng trong văn viết trang trọng, tin tức, IELTS Writing.",
  mistake:["He is said that he is rich.","It is said that he is rich. / He is said to be rich.","Không trộn hai cấu trúc với nhau."],
  xf:{la:"Chủ động",lb:"Bị động",a:"{1:People} {2:say} that {3:he} is rich.",b:"{3:He} {2:is said} to be rich."}},
 {id:"p-causative",num:"07",en:"Causative have / get",vi:"Thể nhờ bảo",short:"have / get + O + V3",
  core:"Dùng khi <strong>nhờ hoặc thuê người khác làm</strong> việc gì cho mình. Cũng dùng cho việc không may xảy ra với mình.",
  forms:[["have","have + O (vật) + V3","I <mark>had my hair cut</mark>."],["get","get + O (vật) + V3 (thân mật hơn)","I <mark>got my car repaired</mark>."],["act","have + người + V / get + người + to V","I <mark>had him fix</mark> it. / I <mark>got him to fix</mark> it."]],
  uses:[["Dịch vụ","I'm <mark>having my house painted</mark> next week."],["Việc không may","She <mark>had her bag stolen</mark> on the bus."]],
  signals:["have something done","get something done"],tenses:[],
  speak:5,write:3,reg:"Rất tự nhiên khi nói về dịch vụ hằng ngày: cắt tóc, sửa xe, giao hàng.",
  mistake:["I cut my hair at the salon.","I had my hair cut at the salon.","Nếu người khác làm cho mình, dùng have + O + V3."],
  xf:{la:"Chủ động",lb:"Nhờ bảo",a:"{1:The mechanic} {2:repaired} {3:my car}.",b:"I had {3:my car} {2:repaired}."}},
 {id:"p-not",num:"08",en:"When not to use passive",vi:"Khi không dùng bị động",short:"happen, arrive, die, seem…",big:"happen · arrive · die · seem · resemble",
  core:"Chỉ <strong>ngoại động từ</strong> (có tân ngữ) mới có bị động. Nội động từ và một số động từ trạng thái không chuyển được.",
  forms:[["✗","Nội động từ: happen, arrive, die, occur, disappear","The accident <mark>happened</mark> at night."],["✗","Động từ trạng thái: have (sở hữu), resemble, fit, suit","She <mark>resembles</mark> her mother."],["✓","Ngoại động từ có tân ngữ: build, write, make","The bridge <mark>was built</mark> in 1990."]],
  uses:[["Lỗi rất hay gặp với happen","What <mark>happened</mark>? (không phải was happened)"],["Lỗi với appear, seem","He <mark>seems</mark> tired. (không phải is seemed)"]],
  signals:["happen","occur","arrive","die","seem","resemble"],tenses:[],
  speak:4,write:4,reg:"Lỗi “was happened” rất phổ biến ở người học Việt Nam vì tiếng Việt hay nói “đã bị xảy ra”.",
  mistake:["The accident was happened yesterday.","The accident happened yesterday.","happen là nội động từ, không có bị động."]},
];


registerRows("passive", PV);
GRAMMAR.theory["passive"] = { rows: PV, first: "p-basic" };
})();
