/* content/theory/relative.js: lesson data for this module (edit freely) */
(() => {
const RCV=[
 {id:"rc-who",num:"01",en:"who / whom",vi:"Người: who, whom",short:"người + who / whom",
  core:"who thay cho <strong>người</strong>, làm chủ ngữ hoặc tân ngữ. whom chỉ làm tân ngữ và trang trọng hơn.",
  forms:[["S","N (người) + who + V","The girl <mark>who lives</mark> next door is a nurse."],["O","N (người) + who / whom + S + V","The man <mark>whom</mark> I met was kind."],["prep","giới từ + whom (trang trọng)","The person <mark>to whom</mark> I spoke was helpful."]],
  uses:[["Mô tả, xác định một người","My sister is the one <mark>who</mark> plays the violin."],["Văn viết trang trọng dùng whom","The candidate <mark>whom</mark> we interviewed was excellent."]],
  signals:["who","whom","to whom","with whom"],tenses:[],
  speak:5,write:5,reg:"Khi nói gần như luôn dùng who hoặc that, kể cả ở vị trí tân ngữ. whom gặp chủ yếu trong văn viết trang trọng.",
  mistake:["The man which helped me was kind.","The man who helped me was kind.","Người dùng who, không dùng which."],
  xf:{la:"Hai câu",lb:"Một câu",a:"{1:The girl} is a nurse. {1:She} {2:lives next door}.",b:"{1:The girl} {2:who lives next door} is a nurse.",note:"She (chủ ngữ) được thay bằng who; mệnh đề đứng ngay sau danh từ nó bổ nghĩa."}},
 {id:"rc-which",num:"02",en:"which",vi:"Vật: which",short:"vật + which",
  core:"which thay cho <strong>vật, con vật</strong>. Sau dấu phẩy, which còn có thể thay cho <strong>cả mệnh đề phía trước</strong>.",
  forms:[["S","N (vật) + which + V","The phone <mark>which is</mark> on the table is mine."],["O","N (vật) + which + S + V","The book <mark>which</mark> I bought was cheap."],["prep","giới từ + which","The house <mark>in which</mark> I grew up is old."],["all",", which (thay cả mệnh đề)","He passed the exam<mark>, which</mark> surprised everyone."]],
  uses:[["Mô tả đồ vật","I lost the keys <mark>which</mark> you gave me."],["Bình luận cả câu phía trước","It rained all day<mark>, which</mark> ruined our picnic."]],
  signals:["which","in which","of which",", which"],tenses:[],
  speak:4,write:5,reg:"Khi nói, mệnh đề xác định hay dùng that thay cho which. Văn viết dùng which nhiều hơn.",
  mistake:["He was late, that made me angry.","He was late, which made me angry.","Thay cho cả mệnh đề phải dùng which, không dùng that."],
  xf:{la:"Hai câu",lb:"Một câu",a:"{1:The phone} is mine. {1:It} {2:is on the table}.",b:"{1:The phone} {2:which is on the table} is mine."}},
 {id:"rc-that",num:"03",en:"that",vi:"that: người và vật",short:"người / vật + that",
  core:"that thay được cho cả người và vật trong <strong>mệnh đề xác định</strong> (không có dấu phẩy). Có chỗ bắt buộc dùng that và có chỗ không được dùng.",
  forms:[["✓","Sau so sánh nhất, the first, the only, all, everything, nothing","It's the best film <mark>that</mark> I've ever seen."],["✓","Sau danh từ gồm cả người và vật","The people and animals <mark>that</mark> live here…"],["✗","Không dùng sau dấu phẩy","My mother<mark>, who</mark> is a teacher, … (không dùng that)"],["✗","Không dùng sau giới từ","the house <mark>in which</mark> … (không dùng in that)"]],
  uses:[["Giao tiếp hằng ngày","Is this the bus <mark>that</mark> goes to the airport?"],["Sau so sánh nhất","She's the kindest person <mark>that</mark> I know."]],
  signals:["that","the only … that","everything that","the best … that"],tenses:[],
  speak:5,write:4,reg:"Rất tự nhiên khi nói. Trong văn viết học thuật, nhiều người ưu tiên which cho vật.",
  mistake:["My laptop, that is new, is fast.","My laptop, which is new, is fast.","Sau dấu phẩy không dùng that."],
  xf:{la:"Hai câu",lb:"Một câu",a:"{1:It's the best film}. {2:I've ever seen it}.",b:"{1:It's the best film} {2:that I've ever seen}."}},
 {id:"rc-whose",num:"04",en:"whose",vi:"Sở hữu: whose",short:"N + whose + N",
  core:"whose thay cho <strong>tính từ sở hữu</strong> (his, her, its, their) và luôn có một danh từ đi ngay sau.",
  forms:[["+","N + whose + N + V","The boy <mark>whose bike</mark> was stolen is crying."],["vật","whose dùng được cho cả vật","a company <mark>whose</mark> products are popular"]],
  uses:[["Nói về đồ vật, người thân của ai","I know a woman <mark>whose</mark> son is a pilot."],["Mô tả tổ chức, địa danh","It's a city <mark>whose</mark> history goes back 1,000 years."]],
  signals:["whose + danh từ"],tenses:[],
  speak:3,write:4,reg:"Dùng được cả khi nói lẫn viết. Người học hay quên rằng sau whose phải có danh từ.",
  mistake:["The man who his car broke down called us.","The man whose car broke down called us.","whose đã thay cho his, không lặp lại tính từ sở hữu."],
  xf:{la:"Hai câu",lb:"Một câu",a:"{1:The boy} is crying. {2:His} bike was stolen.",b:"{1:The boy} {2:whose} bike was stolen is crying."}},
 {id:"rc-adverbs",num:"05",en:"where / when / why",vi:"Nơi chốn, thời gian, lý do",short:"where · when · why",
  core:"where thay cho <strong>nơi chốn</strong>, when cho <strong>thời gian</strong>, why cho <strong>lý do</strong> (sau the reason).",
  forms:[["where","N (nơi) + where + S + V = in / at which","This is the café <mark>where</mark> we first met."],["when","N (thời gian) + when + S + V = on / in which","I remember the day <mark>when</mark> I got my first job."],["why","the reason + why + S + V","That's the reason <mark>why</mark> I left."]],
  uses:[["Kể kỷ niệm","Da Lat is the city <mark>where</mark> I grew up."],["Giải thích","Nobody knows the reason <mark>why</mark> she quit."]],
  signals:["where","when","why","in which","on which"],tenses:[],
  speak:5,write:4,reg:"Dùng nhiều khi kể chuyện và mô tả. Văn viết trang trọng hay thay bằng in which, on which.",
  mistake:["This is the house where I was born in.","This is the house where I was born.","where đã bao gồm giới từ, không thêm in."],
  xf:{la:"Hai câu",lb:"Một câu",a:"{1:This is the café}. We first met {2:there}.",b:"{1:This is the café} {2:where} we first met."}},
 {id:"rc-defining",num:"06",en:"Defining vs non-defining",vi:"Xác định và không xác định",short:"không dấu phẩy · có dấu phẩy",
  core:"Mệnh đề <strong>xác định</strong> cho biết đang nói về ai, cái nào, không có dấu phẩy. Mệnh đề <strong>không xác định</strong> chỉ thêm thông tin, đặt giữa hai dấu phẩy và không dùng that.",
  forms:[["D","N + who / which / that + … (không dấu phẩy)","Students <mark>who study hard</mark> pass."],["ND","N, + who / which + … , (có dấu phẩy)","My brother<mark>, who lives in Hue,</mark> is a doctor."],["!","Tên riêng, my + N duy nhất: không xác định","Hanoi<mark>, which</mark> is the capital, is busy."]],
  uses:[["Thêm thông tin phụ","Mr Nam<mark>, who</mark> teaches us maths, is retiring."],["Dấu phẩy đổi nghĩa câu","My sister who lives in Hue (có nhiều chị) / My sister, who lives in Hue, (chỉ một chị)"]],
  signals:["dấu phẩy","tên riêng","my + danh từ"],tenses:[],
  speak:3,write:5,reg:"Khi nói, mệnh đề không xác định thể hiện bằng chỗ ngắt giọng. Trong văn viết, dấu phẩy làm thay đổi nghĩa câu.",
  mistake:["Ho Chi Minh City that is the biggest city is busy.","Ho Chi Minh City, which is the biggest city, is busy.","Tên riêng cần mệnh đề không xác định: dấu phẩy + which."],
  xf:{la:"Xác định",lb:"Không xác định",a:"{1:My sister} {2:who lives in Hue} is a doctor.",b:"{1:My sister}{2:, who lives in Hue,} is a doctor.",note:"Câu 1: tôi có nhiều chị, đang nói người sống ở Huế. Câu 2: tôi chỉ có một chị, chuyện ở Huế là thông tin thêm."}},
 {id:"rc-omit",num:"07",en:"Omitting the pronoun",vi:"Lược bỏ đại từ quan hệ",short:"N + (that) + S + V",
  core:"Khi đại từ quan hệ làm <strong>tân ngữ</strong> trong mệnh đề xác định thì có thể bỏ. Khi làm chủ ngữ hoặc đứng sau dấu phẩy thì phải giữ.",
  forms:[["✓","Tân ngữ: N + (who / which / that) + S + V","The book (<mark>that</mark>) I bought was cheap."],["✗","Chủ ngữ: phải giữ","The man <mark>who</mark> called you is here."],["✗","Không xác định: phải giữ","My car<mark>, which</mark> I bought last year, is red."]],
  uses:[["Nói tự nhiên, ngắn gọn","Is this the song you like?"],["Mẹo nhận biết","Sau đại từ là một chủ ngữ khác (I, you, she…) thì bỏ được."]],
  signals:["N + S + V","the one I …","the thing you …"],tenses:[],
  speak:5,write:3,reg:"Người bản xứ bỏ đại từ rất thường xuyên khi nói. Văn viết trang trọng hay giữ lại cho rõ.",
  mistake:["The man called you is here.","The man who called you is here.","who làm chủ ngữ nên không bỏ được."],
  xf:{la:"Đầy đủ",lb:"Lược bỏ",a:"The book {1:that} {2:I bought} was cheap.",b:"The book {2:I bought} was cheap.",note:"that làm tân ngữ của bought nên bỏ được."}},
 {id:"rc-reduced",num:"08",en:"Reduced clauses",vi:"Rút gọn mệnh đề quan hệ",short:"V-ing · V3 · to V",
  core:"Rút gọn mệnh đề quan hệ thành <strong>V-ing, V3 hoặc to V</strong> để câu ngắn gọn hơn.",
  forms:[["V-ing","Chủ động: bỏ who / which, V thành V-ing","The man <mark>standing</mark> there is my boss."],["V3","Bị động: bỏ who / which + be, giữ V3","The cars <mark>made</mark> in Japan are reliable."],["to V","Sau the first, the last, the only, so sánh nhất","She was the first <mark>to arrive</mark>."]],
  uses:[["Văn viết gọn","Students <mark>wishing</mark> to join should sign up."],["Báo cáo, bài học thuật","The data <mark>collected</mark> in 2024 shows a clear trend."]],
  signals:["V-ing","V3","the first to"],tenses:[],
  speak:3,write:5,reg:"Gặp rất nhiều trong IELTS Writing và văn bản trang trọng.",
  mistake:["The man stood there is my boss.","The man standing there is my boss.","Rút gọn chủ động dùng V-ing."],
  xf:{la:"Đầy đủ",lb:"Rút gọn",a:"The man {1:who is standing} there is my boss.",b:"The man {1:standing} there is my boss."}},
];


registerRows("relative", RCV);
GRAMMAR.theory["relative"] = { rows: RCV, first: "rc-who" };
})();
