/* content/theory/wish.js: lesson data for this module (edit freely) */
(() => {
const WV=[
 {id:"w-present",num:"01",en:"Wish: present",vi:"Ước ở hiện tại",short:"wish + V2 (were)",
  core:"Ước điều <strong>trái với hiện tại</strong>. Động từ lùi về quá khứ đơn; be dùng were cho mọi ngôi.",
  tl:[{t:"if",x:360,real:false,s:"I wish I were taller"},{t:"label",x:500,y:130,s:"thực tế: I'm not tall"}],
  forms:[["+","S + wish + S + V2/ed","I <mark>wish</mark> I <mark>had</mark> a car."],["be","S + wish + S + were","She <mark>wishes</mark> she <mark>were</mark> taller."],["−","S + wish + S + didn't + V","I <mark>wish</mark> I <mark>didn't have</mark> to work today."]],
  uses:[["Không hài lòng với hiện tại","I <mark>wish</mark> I <mark>lived</mark> near the beach."],["Ước tình huống khác đi","I <mark>wish</mark> it <mark>weren't</mark> so hot."]],
  signals:["wish","were","didn't"],tensesLabel:"Thì dùng sau wish",tenses:[["Lùi về","pas"]],
  speak:5,write:4,reg:"Rất phổ biến khi nói. Văn nói thân mật đôi khi nghe I wish I was…, nhưng bài thi nên dùng were.",
  mistake:["I wish I am rich.","I wish I were rich.","Ước trái hiện tại phải lùi thì."]},
 {id:"w-past",num:"02",en:"Wish: past",vi:"Ước về quá khứ, tiếc nuối",short:"wish + had V3",
  core:"Tiếc nuối về một việc <strong>đã xảy ra hoặc đã không xảy ra</strong> trong quá khứ.",
  tl:[{t:"if",x:180,real:false,s:"I wish I had studied"},{t:"arrow",x1:195,x2:352},{t:"label",x:270,y:130,s:"bây giờ tiếc nuối"}],
  forms:[["+","S + wish + S + had + V3","I <mark>wish</mark> I <mark>had studied</mark> harder."],["−","S + wish + S + hadn't + V3","She <mark>wishes</mark> she <mark>hadn't said</mark> that."],["could","S + wish + S + could have + V3","I <mark>wish</mark> I <mark>could have come</mark>."]],
  uses:[["Tiếc việc mình đã làm","I <mark>wish</mark> I <mark>hadn't eaten</mark> so much."],["Tiếc việc mình đã không làm","He <mark>wishes</mark> he <mark>had taken</mark> the job."]],
  signals:["had + V3","hadn't","could have"],tensesLabel:"Thì dùng sau wish",tenses:[["Lùi về","pap"]],
  speak:4,write:4,reg:"Dùng nhiều khi nói về những lựa chọn trong quá khứ. Hay đi cùng câu điều kiện loại 3.",
  mistake:["I wish I studied harder last year.","I wish I had studied harder last year.","Có last year (quá khứ) thì dùng had + V3."]},
 {id:"w-would",num:"03",en:"Wish + would",vi:"Muốn người khác, sự việc thay đổi",short:"wish + O + would + V",
  core:"Dùng để <strong>phàn nàn</strong> hoặc mong người khác, sự việc thay đổi. Không dùng would khi ước về chính mình (I wish I would ✗).",
  tl:[{t:"if",x:540,real:false,s:"I wish it would stop raining"}],
  forms:[["+","S + wish + O + would + V","I <mark>wish</mark> you <mark>would listen</mark> to me."],["−","S + wish + O + wouldn't + V","I <mark>wish</mark> he <mark>wouldn't talk</mark> so loudly."]],
  uses:[["Phàn nàn thói quen của người khác","I <mark>wish</mark> my neighbours <mark>would turn</mark> the music down."],["Mong thời tiết, tình huống thay đổi","I <mark>wish</mark> it <mark>would stop</mark> raining."]],
  signals:["would","wouldn't"],tenses:[],
  speak:5,write:3,reg:"Rất hay dùng khi nói để bày tỏ khó chịu một cách nhẹ nhàng.",
  mistake:["I wish I would be taller.","I wish I were taller.","Ước về chính mình không dùng would; dùng V2."]},
 {id:"w-could",num:"04",en:"Wish + could",vi:"Ước có khả năng",short:"wish + could + V",
  core:"Ước mình <strong>có thể làm được</strong> điều gì đó ở hiện tại, hoặc đã làm được trong quá khứ.",
  tl:[{t:"if",x:360,real:false,s:"I wish I could swim"}],
  forms:[["now","S + wish + S + could + V","I <mark>wish</mark> I <mark>could speak</mark> Japanese."],["past","S + wish + S + could have + V3","I <mark>wish</mark> I <mark>could have helped</mark> you."]],
  uses:[["Kỹ năng mong muốn","I <mark>wish</mark> I <mark>could play</mark> the guitar."],["Từ chối lịch sự","I <mark>wish</mark> I <mark>could</mark> come, but I'm busy."]],
  signals:["could","could have"],tenses:[],
  speak:5,write:3,reg:"“I wish I could, but…” là cách từ chối lời mời rất lịch sự.",
  mistake:["I wish I can swim.","I wish I could swim.","can lùi thành could."]},
 {id:"w-ifonly",num:"05",en:"If only",vi:"If only: ước mạnh hơn",short:"If only + V2 / had V3",
  core:"If only có cùng cấu trúc với wish nhưng <strong>cảm xúc mạnh hơn</strong>, thường dùng như một câu cảm thán.",
  tl:[{t:"if",x:170,real:false,s:"If only I had known!"},{t:"if",x:420,real:false,s:"If only I had more time!"}],
  forms:[["now","If only + S + V2 (were)","<mark>If only</mark> I <mark>had</mark> more time!"],["past","If only + S + had + V3","<mark>If only</mark> I <mark>had listened</mark> to you!"],["fut","If only + S + would + V","<mark>If only</mark> he <mark>would</mark> call!"]],
  uses:[["Tiếc nuối mạnh","<mark>If only</mark> I <mark>hadn't missed</mark> the train!"],["Mong ước nhiều cảm xúc","<mark>If only</mark> we <mark>were</mark> on holiday now."]],
  signals:["If only"],tenses:[],
  speak:4,write:3,reg:"Hay gặp trong văn kể chuyện, phim và lời bài hát. Khi nói, If only thường đứng một mình như câu cảm thán.",
  mistake:["If only I know the answer!","If only I knew the answer!","If only lùi thì giống wish."]},
 {id:"w-similar",num:"06",en:"It's time · would rather · as if",vi:"Cấu trúc lùi thì tương tự",short:"It's time · would rather · as if",big:"It's time · would rather · as if",
  core:"Ba cấu trúc này cũng <strong>lùi thì về quá khứ</strong> để nói điều chưa xảy ra hoặc không có thật ở hiện tại.",
  forms:[["time","It's (high) time + S + V2","<mark>It's time</mark> we <mark>left</mark>."],["rather","S + would rather + S + V2","I<mark>'d rather</mark> you <mark>didn't</mark> smoke here."],["as if","as if / as though + S + V2 (không thật)","He talks <mark>as if</mark> he <mark>knew</mark> everything."]],
  uses:[["Thúc giục","<mark>It's high time</mark> you <mark>found</mark> a job."],["Mong người khác làm khác đi","I<mark>'d rather</mark> you <mark>came</mark> tomorrow."],["So sánh không có thật","She acts <mark>as if</mark> she <mark>were</mark> the boss."]],
  signals:["It's time","It's high time","would rather","as if","as though"],tenses:[],
  speak:4,write:4,reg:"It's time và would rather dùng nhiều khi nói. as if hay gặp trong văn kể chuyện, mô tả.",
  mistake:["It's time we go home.","It's time we went home.","Sau It's time + S dùng quá khứ đơn."]},
];


registerRows("wish", WV);
GRAMMAR.theory["wish"] = { rows: WV, first: "w-present" };
})();
