/* content/theory/cond.js: lesson data for this module (edit freely) */
(() => {
const C=[
 {id:"c-zero",num:"0",real:true,en:"Zero Conditional",vi:"Câu điều kiện loại 0",short:"If + HTĐ, HTĐ",
  core:"Diễn tả <strong>sự thật, quy luật luôn đúng</strong>: hễ điều kiện xảy ra thì kết quả chắc chắn xảy ra. If có thể thay bằng when.",
  forms:[["If","If + S + V(s/es)","If you <mark>heat</mark> ice, …"],["→","S + V(s/es)","… it <mark>melts</mark>."],["⇄","Đảo vế thì bỏ dấu phẩy","Ice <mark>melts</mark> if you <mark>heat</mark> it."]],
  uses:[["Sự thật khoa học","If you <mark>heat</mark> ice, it <mark>melts</mark>."],["Thói quen, quy tắc của bản thân","If I <mark>drink</mark> coffee at night, I <mark>can't</mark> sleep."],["Hướng dẫn, nội quy (vế chính là mệnh lệnh)","If the alarm <mark>rings</mark>, <mark>leave</mark> the building."]],
  signals:["when","whenever","every time","always"],tenses:[["Vế If","ps"],["Vế chính","ps"]],
  speak:4,write:4,reg:"Gặp nhiều trong sách khoa học, hướng dẫn sử dụng và nội quy. Khi nói, hay dùng để kể thói quen của bản thân.",
  mistake:["If you will heat ice, it melts.","If you heat ice, it melts.","Không dùng will trong vế If."],
  tl:[{t:"band",x1:30,x2:690,s:"luôn đúng, mọi lúc"},{t:"if",x:310,real:true,s:"If you heat ice"},{t:"link",x1:310,x2:430},{t:"res",x:430,real:true,s:"it melts"}]},

 {id:"c-first",num:"1",real:true,en:"First Conditional",vi:"Câu điều kiện loại 1",short:"If + HTĐ, will + V",
  core:"Điều kiện <strong>có thể xảy ra</strong> ở hiện tại hoặc tương lai, và kết quả có khả năng xảy ra theo.",
  forms:[["If","If + S + V(s/es)","If it <mark>rains</mark> tomorrow, …"],["→","S + will / can / may + V","… we <mark>will stay</mark> home."],["⇄","Đảo vế thì bỏ dấu phẩy","We<mark>'ll stay</mark> home if it <mark>rains</mark>."]],
  uses:[["Khả năng có thật trong tương lai","If it <mark>rains</mark> tomorrow, we <mark>will stay</mark> home."],["Lời hứa, cảnh báo, đe dọa","If you <mark>touch</mark> that, you<mark>'ll get</mark> burned."],["Đề nghị, nhắc nhở (vế chính là mệnh lệnh)","If you <mark>see</mark> Lan, <mark>tell</mark> her to call me."]],
  signals:["unless","as long as","provided that","as soon as","when (tương lai)"],tenses:[["Vế If","ps"],["Vế chính","fs"]],
  speak:5,write:5,reg:"Loại dùng nhiều nhất trong giao tiếp hằng ngày và email công việc, ví dụ “If you have any questions, please let me know.”",
  extra:"<b>Unless = If … not.</b> “Unless you hurry, you'll miss the bus” nghĩa là “If you don't hurry, you'll miss the bus.”",
  mistake:["If it will rain, we will stay home.","If it rains, we will stay home.","Vế If dùng hiện tại đơn, không dùng will."],
  tl:[{t:"if",x:470,real:true,s:"If it rains"},{t:"link",x1:470,x2:610},{t:"res",x:610,real:true,s:"we'll stay home"}]},

 {id:"c-second",num:"2",real:false,en:"Second Conditional",vi:"Câu điều kiện loại 2",short:"If + V2, would + V",
  core:"Điều kiện <strong>không có thật hoặc khó xảy ra</strong> ở hiện tại hoặc tương lai. Dùng để tưởng tượng và khuyên nhủ.",
  forms:[["If","If + S + V2/ed (be → were)","If I <mark>were</mark> rich, …"],["→","S + would / could / might + V","… I <mark>would travel</mark> the world."],["⇄","Đảo vế thì bỏ dấu phẩy","I<mark>'d travel</mark> the world if I <mark>were</mark> rich."]],
  uses:[["Tưởng tượng trái với hiện tại","If I <mark>had</mark> more time, I <mark>would learn</mark> Japanese."],["Tình huống khó xảy ra trong tương lai","If I <mark>won</mark> the lottery, I <mark>would buy</mark> a house."],["Lời khuyên với If I were you","If I <mark>were</mark> you, I <mark>would talk</mark> to her."]],
  signals:["If I were you","would","could","might"],tenses:[["Vế If","pas"],["Vế chính","would + V"]],
  speak:5,write:4,reg:"Rất hay dùng khi nói để tưởng tượng và khuyên. Văn viết trang trọng dùng were cho mọi ngôi (If he were…), văn nói thân mật đôi khi nghe If he was…",
  mistake:["If I would have money, I would buy it.","If I had money, I would buy it.","Không dùng would trong vế If."],
  tl:[{t:"if",x:330,real:false,s:"If I were rich"},{t:"link",x1:330,x2:470},{t:"res",x:470,real:false,s:"I would travel"}]},

 {id:"c-third",num:"3",real:false,en:"Third Conditional",vi:"Câu điều kiện loại 3",short:"If + had V3, would have V3",
  core:"Điều kiện <strong>trái với sự thật trong quá khứ</strong>. Việc đã không xảy ra nên kết quả cũng chỉ là tưởng tượng, thường mang ý tiếc nuối hoặc trách móc.",
  forms:[["If","If + S + had + V3/ed","If I <mark>had studied</mark> harder, …"],["→","S + would / could / might + have + V3","… I <mark>would have passed</mark>."],["⇄","Đảo vế thì bỏ dấu phẩy","I<mark>'d have passed</mark> if I <mark>had studied</mark>."]],
  uses:[["Tiếc nuối về quá khứ","If I <mark>had studied</mark> harder, I <mark>would have passed</mark> the exam."],["Trách móc, phê bình","If you <mark>had told</mark> me, I <mark>could have helped</mark>."],["Phân tích nguyên nhân","If the driver <mark>had slowed</mark> down, the accident <mark>wouldn't have happened</mark>."]],
  signals:["had + V3","would have","could have","might have"],tenses:[["Vế If","pap"],["Vế chính","would have + V3"]],
  speak:3,write:4,reg:"Gặp nhiều trong văn viết, báo chí phân tích và kể chuyện. Khi nói hay rút gọn: I would have known nghe thành “I'd've known”.",
  mistake:["If I would have known, I would have come.","If I had known, I would have come.","Vế If dùng had + V3, không dùng would have."],
  tl:[{t:"if",x:120,real:false,s:"If I had studied"},{t:"link",x1:120,x2:270},{t:"res",x:270,real:false,s:"would have passed"}]},

 {id:"c-mix-past",num:"3→2",real:false,en:"Mixed: past → present",vi:"Hỗn hợp: quá khứ → hiện tại",short:"If + had V3, would + V",
  core:"Điều kiện <strong>trái với quá khứ</strong>, kết quả <strong>trái với hiện tại</strong>. Một việc đã không xảy ra nên bây giờ mọi thứ khác đi.",
  forms:[["If","If + S + had + V3/ed","If I <mark>had taken</mark> that job, …"],["→","S + would / could + V (now)","… I <mark>would be</mark> rich now."],["⇄","Đảo vế thì bỏ dấu phẩy","I<mark>'d be</mark> rich now if I <mark>had taken</mark> it."]],
  uses:[["Việc quá khứ ảnh hưởng hiện tại","If I <mark>had taken</mark> that job, I <mark>would be</mark> rich now."],["Hậu quả còn kéo dài đến nay","If she <mark>hadn't missed</mark> the flight, she <mark>would be</mark> in Paris now."]],
  signals:["now","today","still"],tenses:[["Vế If","pap"],["Vế chính","would + V"]],
  speak:2,write:3,reg:"Dùng khi muốn nói rõ hệ quả ở hiện tại. Hay xuất hiện trong bài viết và phần thảo luận của bài thi nói.",
  mistake:["If I had taken the job, I would have been rich now.","If I had taken the job, I would be rich now.","Có now ở vế chính thì dùng would + V."],
  tl:[{t:"if",x:150,real:false,s:"If I had taken the job"},{t:"link",x1:150,x2:380},{t:"res",x:380,real:false,s:"I would be rich now"}]},

 {id:"c-mix-present",num:"2→3",real:false,en:"Mixed: present → past",vi:"Hỗn hợp: hiện tại → quá khứ",short:"If + V2, would have V3",
  core:"Điều kiện <strong>trái với hiện tại</strong> (một đặc điểm lâu dài), kết quả <strong>trái với quá khứ</strong>.",
  forms:[["If","If + S + V2/ed (be → were)","If I <mark>weren't</mark> so shy, …"],["→","S + would / could + have + V3","… I <mark>would have spoken</mark> to her."],["⇄","Đảo vế thì bỏ dấu phẩy","I<mark>'d have spoken</mark> to her if I <mark>weren't</mark> shy."]],
  uses:[["Tính cách, trạng thái lâu dài giải thích việc đã qua","If I <mark>weren't</mark> so shy, I <mark>would have spoken</mark> to her at the party."],["Khả năng hiện tại","If he <mark>spoke</mark> English, he <mark>would have got</mark> the job last month."]],
  signals:["tính cách, trạng thái (vế If)","yesterday, last week (vế chính)"],tenses:[["Vế If","pas"],["Vế chính","would have + V3"]],
  speak:2,write:2,reg:"Ít gặp nhất. Dùng khi một đặc điểm cố định của ai đó giải thích chuyện đã xảy ra.",
  mistake:["If I wasn't shy, I would speak to her yesterday.","If I weren't shy, I would have spoken to her yesterday.","Kết quả ở quá khứ (yesterday) cần would have + V3."],
  tl:[{t:"band",x1:250,x2:560,s:"đặc điểm lâu dài"},{t:"if",x:420,real:false,s:"If I weren't so shy"},{t:"link",x1:420,x2:170},{t:"res",x:170,real:false,s:"would have spoken"}]},
];
const V=[
 {id:"c-unless",num:"+",en:"Unless",vi:"Unless = If … not",short:"Unless + khẳng định",big:"Unless = If … not",
  core:"Unless nghĩa là <strong>trừ khi, nếu không</strong>. Vế unless luôn ở dạng khẳng định vì bản thân từ này đã mang nghĩa phủ định.",
  forms:[["=","Unless + S + V","<mark>Unless</mark> you hurry, you'll miss the bus."],["=","If + S + do/does not + V","<mark>If</mark> you <mark>don't</mark> hurry, you'll miss the bus."]],
  uses:[["Cảnh báo","<mark>Unless</mark> you study, you will fail."],["Điều kiện bắt buộc","You can't enter <mark>unless</mark> you have a ticket."]],
  signals:["unless","= if … not"],tenses:[["Vế Unless","ps"],["Vế chính","fs"]],
  speak:4,write:4,reg:"Hay dùng trong lời cảnh báo và điều khoản. Thường đi với câu điều kiện loại 1.",
  mistake:["Unless you don't hurry, you'll be late.","Unless you hurry, you'll be late.","Unless đã mang nghĩa phủ định, không thêm not."]},
 {id:"c-inversion",num:"+",en:"Inversion",vi:"Đảo ngữ câu điều kiện",short:"Should / Were / Had + S",big:"Should · Were · Had",
  core:"Bỏ If và đưa trợ động từ lên đầu câu. Câu <strong>trang trọng hơn</strong>, hay gặp trong văn viết và bài thi.",
  forms:[["L1","Should + S + V, S + will + V","<mark>Should</mark> you need help, call me."],["L2","Were + S + to V / N / Adj, S + would + V","<mark>Were</mark> I rich, I would travel."],["L3","Had + S + V3, S + would have + V3","<mark>Had</mark> I known, I would have come."]],
  uses:[["Email, thư trang trọng","<mark>Should</mark> you have any questions, please contact us."],["Bài viết học thuật","<mark>Had</mark> the government acted earlier, the crisis could have been avoided."]],
  signals:["Should + S","Were + S","Had + S"],tenses:[],
  speak:1,write:4,reg:"Gần như chỉ dùng trong văn viết trang trọng. Dùng khi nói chuyện hằng ngày nghe khá cứng.",
  mistake:["Had I not knew, I would have stayed.","Had I not known, I would have stayed.","Sau Had vẫn dùng V3; phủ định thì thêm not sau chủ ngữ."]},
 {id:"c-alt",num:"+",en:"Other linking words",vi:"Từ thay thế If",short:"provided · as long as · in case",big:"provided · as long as · in case · otherwise · but for",
  core:"Một số từ nối mang nghĩa điều kiện, giúp câu <strong>rõ sắc thái</strong> hơn If.",
  forms:[["≈","provided (that) / providing","You can go <mark>provided that</mark> you finish your homework."],["≈","as long as / so long as","I'll lend you the car <mark>as long as</mark> you drive carefully."],["≠","in case (phòng khi)","Take an umbrella <mark>in case</mark> it rains."]],
  uses:[["provided / as long as: với điều kiện là","You can stay <mark>as long as</mark> you're quiet."],["in case: chuẩn bị trước, phòng khi","Save your work <mark>in case</mark> the power goes out."],["otherwise / or else: nếu không thì","Hurry up, <mark>otherwise</mark> we'll be late."],["but for / without + N: nếu không có","<mark>But for</mark> your help, I would have failed."]],
  signals:["provided that","as long as","in case","otherwise","but for","without"],tenses:[],
  speak:3,write:4,reg:"as long as và in case rất tự nhiên khi nói. provided that và but for trang trọng hơn, hợp với văn viết.",
  mistake:["Take an umbrella if it rains.","Take an umbrella in case it rains.","in case là chuẩn bị trước khi việc xảy ra; if là chỉ làm khi việc đã xảy ra."]},
 {id:"c-wish",num:"+",extra:`<button class="link sm" data-review="w-present">Xem đầy đủ ở mục 07 Câu ước →</button>`,en:"Wish / If only",vi:"Câu ước",short:"wish + lùi một thì",big:"I wish … / If only …",
  core:"Wish và If only diễn tả <strong>mong muốn trái với thực tế</strong>, dùng cách lùi thì giống câu điều kiện.",
  forms:[["HT","S + wish + S + V2/ed (were)","I <mark>wish</mark> I <mark>were</mark> taller."],["QK","S + wish + S + had + V3","I <mark>wish</mark> I <mark>had studied</mark> harder."],["TL","S + wish + S + would + V","I <mark>wish</mark> it <mark>would stop</mark> raining."]],
  uses:[["Tiếc nuối ở hiện tại","<mark>If only</mark> I <mark>had</mark> more free time."],["Tiếc nuối về quá khứ","She <mark>wishes</mark> she <mark>hadn't said</mark> that."],["Phàn nàn, mong người khác thay đổi","I <mark>wish</mark> you <mark>would listen</mark> to me."]],
  signals:["wish","if only"],tenses:[["Ước hiện tại","pas"],["Ước quá khứ","pap"]],
  speak:4,write:3,reg:"Rất hay dùng khi nói để bày tỏ tiếc nuối. If only mạnh và cảm xúc hơn wish.",
  mistake:["I wish I am taller.","I wish I were taller.","Ước trái với hiện tại thì lùi về quá khứ."]},
];


registerRows("cond", C);
registerRows("cond", V);
GRAMMAR.theory["cond"] = { rows: C, first: "c-first", extra: V };
})();
