/* content/theory/modal.js: lesson data for this module (edit freely) */
(() => {
const MV=[
 {id:"m-deduction-present",num:"01",en:"Deduction: present",vi:"Suy đoán ở hiện tại",short:"must · might · can't",
  core:"Dùng modal để nói <strong>mình chắc chắn đến đâu</strong> về một điều ở hiện tại.",
  scale:{left:"chắc chắn không",right:"chắc chắn có",marks:[[3,"can't"],[35,"might / could"],[52,"may"],[75,"should"],[97,"must"]]},
  forms:[["must","must + V (gần như chắc chắn đúng)","She's not answering. She <mark>must be</mark> busy."],["may","may / might / could + V (có thể)","He <mark>might be</mark> at home."],["can't","can't / couldn't + V (chắc chắn không)","That <mark>can't be</mark> true."]],
  uses:[["Đoán dựa trên dấu hiệu","The lights are on. They <mark>must be</mark> home."],["Đưa ra khả năng","Take an umbrella. It <mark>might rain</mark>."]],
  signals:["must be","might be","can't be"],tenses:[],
  speak:5,write:4,reg:"Rất hay dùng khi nói chuyện hằng ngày. Văn viết học thuật thích dùng may, might để thận trọng.",
  mistake:["He mustn't be at home. The lights are off.","He can't be at home. The lights are off.","Đoán phủ định dùng can't, không dùng mustn't."]},
 {id:"m-deduction-past",num:"02",en:"Deduction: past",vi:"Suy đoán về quá khứ",short:"must / might / can't + have V3",
  core:"Suy đoán về việc <strong>đã xảy ra</strong>: dùng modal + have + V3.",
  scale:{left:"chắc chắn không",right:"chắc chắn có",marks:[[3,"can't have V3"],[45,"might have V3"],[97,"must have V3"]]},
  forms:[["must","must have + V3","The ground is wet. It <mark>must have rained</mark>."],["might","may / might / could have + V3","She <mark>might have missed</mark> the bus."],["can't","can't / couldn't have + V3","He <mark>can't have seen</mark> me. I was hiding."]],
  uses:[["Giải thích chuyện đã xảy ra","I can't find my keys. I <mark>must have left</mark> them at work."],["Loại trừ khả năng","She <mark>couldn't have taken</mark> it. She wasn't here."]],
  signals:["must have","might have","can't have"],tenses:[],
  speak:4,write:4,reg:"Khi nói thường rút gọn: must've, might've, could've.",
  mistake:["He must went home.","He must have gone home.","Đoán về quá khứ dùng have + V3 sau modal."]},
 {id:"m-obligation",num:"03",en:"Obligation & prohibition",vi:"Bắt buộc, cấm và không cần",short:"must · have to · mustn't · don't have to",
  core:"Các modal này xếp trên một thang <strong>từ cấm đến bắt buộc</strong>. Cẩn thận: mustn't và don't have to nghĩa rất khác nhau.",
  scale:{left:"cấm",right:"bắt buộc",marks:[[3,"mustn't"],[38,"don't have to"],[64,"should"],[84,"have to"],[97,"must"]]},
  forms:[["must","must + V (người nói thấy cần)","I <mark>must call</mark> my mum."],["have","have to + V (quy định bên ngoài)","I <mark>have to wear</mark> a uniform at work."],["not","mustn't + V (cấm)","You <mark>mustn't smoke</mark> here."],["no","don't have to / needn't + V (không cần)","You <mark>don't have to come</mark> if you're busy."]],
  uses:[["Nội quy, biển báo","Visitors <mark>must</mark> sign in."],["Quá khứ của must là had to","I <mark>had to</mark> work late yesterday."]],
  signals:["must","have to","mustn't","don't have to","needn't"],tenses:[],
  speak:5,write:5,reg:"have to tự nhiên hơn khi nói; must hay gặp trong văn bản, nội quy.",
  mistake:["You mustn't come if you're busy.","You don't have to come if you're busy.","mustn't là cấm; không cần thì dùng don't have to."]},
 {id:"m-advice",num:"04",en:"Advice",vi:"Lời khuyên",short:"should · ought to · had better",
  core:"Từ gợi ý nhẹ nhàng đến lời khuyên mang tính <strong>cảnh báo</strong>.",
  scale:{left:"nhẹ",right:"mạnh",marks:[[25,"could"],[55,"should / ought to"],[85,"had better"],[97,"must"]]},
  forms:[["could","could + V (gợi ý)","You <mark>could try</mark> calling her."],["should","should / ought to + V","You <mark>should see</mark> a doctor."],["better","had better (not) + V (cảnh báo)","You<mark>'d better leave</mark> now or you'll miss the bus."]],
  uses:[["Khuyên bạn bè","You <mark>should</mark> get some rest."],["Cảnh báo có hậu quả","We<mark>'d better not</mark> be late again."]],
  signals:["should","ought to","had better","If I were you"],tenses:[],
  speak:5,write:4,reg:"should dùng mọi lúc. ought to hơi trang trọng. had better mang ý cảnh báo, dùng nhiều khi nói.",
  mistake:["You should to rest.","You should rest.","Sau modal là động từ nguyên mẫu không to (trừ ought to)."]},
 {id:"m-ability",num:"05",en:"Ability",vi:"Khả năng",short:"can · could · be able to",
  core:"Nói về <strong>khả năng</strong> ở quá khứ, hiện tại và tương lai.",
  tl:[{t:"point",x:190,s:"could / was able to"},{t:"point",x:360,s:"can"},{t:"point",x:560,s:"will be able to"}],
  forms:[["can","can / can't + V","I <mark>can speak</mark> three languages."],["could","could + V (khả năng chung trong quá khứ)","I <mark>could swim</mark> when I was five."],["able","was / were able to + V (làm được một lần cụ thể)","The fire spread fast, but everyone <mark>was able to escape</mark>."],["will","will be able to + V","You<mark>'ll be able to drive</mark> after the test."]],
  uses:[["Kỹ năng","She <mark>can play</mark> the piano."],["Thành công trong tình huống khó","After hours of trying, we <mark>were able to</mark> fix it."]],
  signals:["can","could","be able to","manage to"],tensesLabel:"Thì liên quan",tenses:[["Quá khứ","pas"],["Tương lai","fs"]],
  speak:5,write:4,reg:"can và could dùng hằng ngày. be able to cần khi chia các thì mà can không chia được.",
  mistake:["I will can come tomorrow.","I will be able to come tomorrow.","Hai modal không đứng cạnh nhau; dùng be able to."]},
 {id:"m-permission",num:"06",en:"Permission & requests",vi:"Xin phép, yêu cầu",short:"can · could · may · would you mind",
  core:"Các cách xin phép và nhờ vả xếp theo mức độ <strong>từ thân mật đến lịch sự</strong>.",
  scale:{left:"thân mật",right:"lịch sự",marks:[[8,"Can I…?"],[40,"Could you…?"],[70,"May I…?"],[95,"Would you mind…?"]]},
  forms:[["can","Can I / Can you + V?","<mark>Can I borrow</mark> your pen?"],["could","Could I / Could you + V?","<mark>Could you open</mark> the window?"],["may","May I + V? (trang trọng)","<mark>May I come</mark> in?"],["mind","Would you mind + V-ing?","<mark>Would you mind closing</mark> the door?"]],
  uses:[["Nói với bạn bè","<mark>Can you</mark> pass me the salt?"],["Nói với khách hàng, cấp trên","<mark>Could you</mark> send me the file, please?"]],
  signals:["Can I","Could you","May I","Would you mind"],tenses:[],
  speak:5,write:4,reg:"Could you… là lựa chọn an toàn nhất trong email công việc.",
  mistake:["May you help me?","Could you help me?","may chỉ dùng với I, we khi xin phép."]},
 {id:"m-perfect",num:"07",en:"Past regrets & criticism",vi:"Tiếc nuối, trách móc",short:"should have · could have · needn't have",
  core:"Modal + have + V3 nhìn lại quá khứ để nói <strong>điều đáng lẽ nên làm</strong> hoặc đã có thể làm.",
  tl:[{t:"point",x:190,s:"should have V3"},{t:"arrow",x1:205,x2:352},{t:"label",x:280,y:130,s:"bây giờ nhìn lại"}],
  forms:[["should","should have + V3 (đáng lẽ nên)","I <mark>should have studied</mark> harder."],["not","shouldn't have + V3 (đáng lẽ không nên)","You <mark>shouldn't have said</mark> that."],["could","could have + V3 (đã có thể nhưng không)","We <mark>could have won</mark>."],["need","needn't have + V3 (đã làm nhưng không cần)","You <mark>needn't have bought</mark> flowers."]],
  uses:[["Tiếc nuối bản thân","I <mark>should have</mark> left earlier."],["Trách nhẹ người khác","You <mark>could have told</mark> me!"]],
  signals:["should have","could have","needn't have"],tensesLabel:"Thì liên quan",tenses:[["Giống ý","pap"]],
  speak:5,write:3,reg:"Rất tự nhiên khi nói. Thường rút gọn: should've, could've.",
  mistake:["I should studied harder.","I should have studied harder.","Nói về quá khứ cần have + V3."]},
 {id:"m-habits",num:"08",en:"Past habits: used to & would",vi:"Thói quen trong quá khứ",short:"used to · would",
  core:"Kể về <strong>thói quen, trạng thái ngày xưa</strong> mà bây giờ không còn.",
  tl:[{t:"dots",xs:[60,110,160,210,260]},{t:"label",x:160,y:130,s:"used to / would"}],
  forms:[["used","used to + V (thói quen và trạng thái)","I <mark>used to live</mark> in Hue."],["would","would + V (chỉ hành động lặp lại)","Every summer we <mark>would go</mark> to the beach."],["be","be / get used to + V-ing (quen với)","I'm <mark>used to getting</mark> up early."]],
  uses:[["Kể chuyện tuổi thơ","When I was a kid, I <mark>used to</mark> climb trees."],["Văn kể chuyện, hồi ký","My grandfather <mark>would</mark> tell us stories every night."]],
  signals:["used to","would","didn't use to"],tensesLabel:"Thì liên quan",tenses:[["Giống ý","pas"]],
  speak:5,write:4,reg:"used to dùng nhiều khi nói. would cho thói quen hay xuất hiện trong văn kể chuyện.",
  mistake:["I would live in Hue.","I used to live in Hue.","would không dùng cho trạng thái (live, have, be)."]},
];


registerRows("modal", MV);
GRAMMAR.theory["modal"] = { rows: MV, first: "m-deduction-present" };
})();
