/* content/theory/reported.js: lesson data for this module (edit freely) */
(() => {
const RV=[
 {id:"r-backshift",num:"01",en:"Tense backshift",vi:"Lùi thì",short:"am → was · will → would",
  core:"Khi động từ tường thuật ở quá khứ (said, told, asked), động từ trong lời nói <strong>lùi về quá khứ một bậc</strong>.",
  forms:[["1","Hiện tại đơn → Quá khứ đơn","“I <mark>am</mark> tired.” → She said she <mark>was</mark> tired."],["2","Hiện tại tiếp diễn → Quá khứ tiếp diễn","“I<mark>'m working</mark>.” → He said he <mark>was working</mark>."],["3","Hiện tại hoàn thành → Quá khứ hoàn thành","“I<mark>'ve finished</mark>.” → She said she <mark>had finished</mark>."],["4","Quá khứ đơn → Quá khứ hoàn thành","“I <mark>saw</mark> it.” → He said he <mark>had seen</mark> it."],["5","will → would","“I<mark>'ll call</mark>.” → She said she <mark>would call</mark>."],["6","can → could · may → might","“I <mark>can</mark> swim.” → He said he <mark>could</mark> swim."],["7","must → had to (bắt buộc)","“I <mark>must</mark> go.” → She said she <mark>had to</mark> go."]],
  uses:[["Kể lại lời người khác đã nói","“I love this song.” → She said she <mark>loved</mark> that song."],["Viết biên bản, tóm tắt cuộc họp","The manager said the project <mark>would be</mark> delayed."]],
  signals:["said","told","asked","explained"],tensesLabel:"Các thì liên quan",tenses:[["Gốc","ps"],["Lùi","pas"],["Gốc","pp"],["Lùi","pap"],["Gốc","fs"]],
  speak:4,write:5,reg:"Khi nói nhanh, người bản xứ đôi khi không lùi thì nếu điều đó vẫn đúng. Trong bài thi và văn viết nên lùi thì đầy đủ.",
  mistake:["She said she is tired yesterday.","She said she was tired.","Động từ tường thuật ở quá khứ thì lùi thì."],
  xf:{la:"Trực tiếp",lb:"Gián tiếp",a:"“{1:I} {2:am} tired,” she said.",b:"She said (that) {1:she} {2:was} tired.",note:"am lùi thành was; I đổi thành she."}},
 {id:"r-words",num:"02",en:"Pronouns, time & place",vi:"Đổi đại từ, thời gian, nơi chốn",short:"today → that day · here → there",
  core:"Ngoài lùi thì, cần <strong>đổi đại từ và từ chỉ thời gian, nơi chốn</strong> cho đúng góc nhìn của người kể lại.",
  forms:[["1","now → then · today → that day","“I'm busy <mark>now</mark>.” → … busy <mark>then</mark>."],["2","yesterday → the day before","“I saw her <mark>yesterday</mark>.” → … <mark>the day before</mark>."],["3","tomorrow → the next day","“See you <mark>tomorrow</mark>.” → … <mark>the next day</mark>."],["4","ago → before · last week → the week before","“two days <mark>ago</mark>” → two days <mark>before</mark>"],["5","here → there · this → that · these → those","“Wait <mark>here</mark>.” → … wait <mark>there</mark>."],["6","I → he/she · my → his/her · we → they","“<mark>My</mark> car” → <mark>his</mark> car"]],
  uses:[["Kể lại sau nhiều ngày, ở nơi khác","“I'll meet you here tomorrow.” → He said he would meet me <mark>there the next day</mark>."]],
  signals:["the day before","the next day","then","there","that"],tenses:[],
  speak:3,write:5,reg:"Trong đời thường, nếu kể lại ngay trong ngày ở cùng chỗ thì không cần đổi. Bài thi thường yêu cầu đổi đầy đủ.",
  mistake:["He said he would come tomorrow. (kể lại tuần sau)","He said he would come the next day.","Nếu thời điểm đã thay đổi, đổi tomorrow thành the next day."],
  xf:{la:"Trực tiếp",lb:"Gián tiếp",a:"“{1:I} will meet you {2:here} {3:tomorrow},” he said.",b:"He said {1:he} would meet me {2:there} {3:the next day}."}},
 {id:"r-statements",num:"03",en:"say vs tell",vi:"Câu kể: say và tell",short:"say (that) · tell + người",
  core:"<strong>tell</strong> luôn cần người nghe ngay sau nó; <strong>say</strong> thì không.",
  forms:[["say","S + said (that) + mệnh đề","She <mark>said</mark> (that) she was busy."],["tell","S + told + người + (that) + mệnh đề","She <mark>told me</mark> (that) she was busy."],["to","say + to + người (ít dùng)","She <mark>said to me</mark> that she was busy."]],
  uses:[["Thuật lại câu kể","“I'm hungry.” → He <mark>said</mark> he was hungry."],["Nhấn mạnh người nghe","He <mark>told his mum</mark> he was hungry."]],
  signals:["said","told me","said that"],tenses:[],
  speak:5,write:5,reg:"that thường được bỏ khi nói. Khi viết trang trọng nên giữ that.",
  mistake:["She said me that she was busy.","She told me that she was busy.","say không đi thẳng với người; dùng tell + người."],
  xf:{la:"Trực tiếp",lb:"Gián tiếp",a:"“{1:I}'m busy,” she said {2:to me}.",b:"She told {2:me} (that) {1:she} was busy."}},
 {id:"r-yesno",num:"04",en:"Yes/No questions",vi:"Câu hỏi Yes/No",short:"asked if / whether + S + V",
  core:"Dùng <strong>if hoặc whether</strong>, đưa câu về <strong>trật tự câu kể</strong> (S + V), bỏ dấu hỏi.",
  forms:[["?","S + asked (+ O) + if / whether + S + V (lùi thì)","He asked <mark>if I was</mark> hungry."]],
  uses:[["Thuật lại câu hỏi Có/Không","“Do you like coffee?” → She asked <mark>if I liked</mark> coffee."],["Câu hỏi lịch sự gián tiếp","Could you tell me <mark>if the bank is</mark> open?"]],
  signals:["asked if","asked whether","wanted to know"],tenses:[],
  speak:4,write:4,reg:"Mẫu câu hỏi gián tiếp (Could you tell me if…) rất hữu ích để hỏi lịch sự khi giao tiếp.",
  mistake:["He asked me was I hungry.","He asked me if I was hungry.","Không đảo ngữ trong câu hỏi gián tiếp."],
  xf:{la:"Trực tiếp",lb:"Gián tiếp",a:"“{2:Are} {1:you} hungry?” he asked.",b:"He asked if {1:I} {2:was} hungry."}},
 {id:"r-wh",num:"05",en:"Wh- questions",vi:"Câu hỏi có từ để hỏi",short:"asked + Wh + S + V",
  core:"Giữ từ để hỏi, rồi viết <strong>S + V như câu kể</strong>. Bỏ do, does, did.",
  forms:[["Wh","S + asked (+ O) + Wh + S + V (lùi thì)","She asked <mark>where I lived</mark>."]],
  uses:[["Thuật lại câu hỏi thông tin","“What time is it?” → He asked <mark>what time it was</mark>."],["Hỏi đường lịch sự","Do you know <mark>where the station is</mark>?"]],
  signals:["asked what","asked where","wanted to know why"],tenses:[],
  speak:4,write:4,reg:"Câu hỏi gián tiếp giúp lời nói lịch sự hơn: “Can you tell me what time it starts?”",
  mistake:["She asked where did I live.","She asked where I lived.","Bỏ did, động từ chia về quá khứ."],
  xf:{la:"Trực tiếp",lb:"Gián tiếp",a:"“Where {2:do} {1:you} {3:live}?” she asked.",b:"She asked where {1:I} {3:lived}."}},
 {id:"r-commands",num:"06",en:"Commands & requests",vi:"Câu mệnh lệnh, yêu cầu",short:"told / asked + O + (not) to V",
  core:"Mệnh lệnh và yêu cầu chuyển thành <strong>to V</strong>. Phủ định thì dùng <strong>not to V</strong>.",
  forms:[["+","S + told / asked + O + to V","He <mark>told me to sit</mark> down."],["−","S + told / asked + O + not to V","She <mark>asked me not to be</mark> late."]],
  uses:[["Mệnh lệnh","“Close the door.” → He <mark>told me to close</mark> the door."],["Yêu cầu lịch sự","“Please help me.” → She <mark>asked me to help</mark> her."]],
  signals:["told … to","asked … to","not to"],tenses:[],
  speak:5,write:4,reg:"Cấu trúc rất ngắn gọn, dùng nhiều khi kể lại lời dặn của sếp, thầy cô, bố mẹ.",
  mistake:["She told me don't be late.","She told me not to be late.","Phủ định dùng not to V."],
  xf:{la:"Trực tiếp",lb:"Gián tiếp",a:"“{2:Sit down},” he said {1:to me}.",b:"He told {1:me} {2:to sit down}."}},
 {id:"r-verbs",num:"07",en:"Reporting verbs",vi:"Động từ tường thuật đặc biệt",short:"promise, advise, suggest…",
  core:"Thay vì luôn dùng said, có thể chọn <strong>động từ thể hiện ý định</strong> của người nói. Mỗi động từ đi với một cấu trúc riêng.",
  forms:[["1","agree, offer, promise, refuse, threaten + to V","He <mark>promised to call</mark> me."],["2","advise, remind, warn, invite, encourage + O + to V","She <mark>advised me to rest</mark>."],["3","suggest, admit, deny, recommend + V-ing","He <mark>suggested going</mark> out."],["4","apologise for, accuse O of, insist on + V-ing","She <mark>apologised for being</mark> late."]],
  uses:[["Viết tóm tắt, kể chuyện","“I didn't take it!” → He <mark>denied taking</mark> it."],["IELTS Writing, email","The manager <mark>reminded us to submit</mark> the report."]],
  signals:["promise","advise","suggest","deny","apologise"],tenses:[],
  speak:2,write:5,reg:"Giúp bài viết đa dạng và chính xác hơn. Khi nói thường đơn giản hóa bằng said hoặc told.",
  mistake:["He suggested me to go.","He suggested going. / He suggested that I go.","suggest không đi với O + to V."],
  xf:{la:"Trực tiếp",lb:"Gián tiếp",a:"“{1:I'm sorry} I'm late,” she said.",b:"She {1:apologised for} being late."}},
 {id:"r-nochange",num:"08",en:"When not to backshift",vi:"Khi không lùi thì",short:"says · sự thật · vẫn đúng",big:"says · sự thật · vẫn còn đúng",
  core:"Không phải lúc nào cũng lùi thì. Bốn trường hợp dưới đây <strong>giữ nguyên thì</strong>.",
  forms:[["1","Động từ tường thuật ở hiện tại: says, has said","He <mark>says</mark> he <mark>is</mark> tired."],["2","Sự thật hiển nhiên","The teacher said the Earth <mark>goes</mark> round the Sun."],["3","Điều vẫn còn đúng lúc kể (tùy chọn)","She said she <mark>lives</mark> in Hanoi."],["4","would, could, should, might; câu điều kiện loại 2, 3","He said he <mark>would</mark> help if he <mark>could</mark>."]],
  uses:[["Truyền đạt tin nhắn ngay lúc đó","Mum <mark>says</mark> dinner <mark>is</mark> ready."]],
  signals:["says","has said","sự thật hiển nhiên"],tenses:[],
  speak:4,write:3,reg:"Rất phổ biến khi chuyển lời ngay tại chỗ (“He says he's running late”).",
  mistake:["The teacher said water boiled at 100°C.","The teacher said water boils at 100°C.","Sự thật hiển nhiên giữ thì hiện tại (cả hai cách đều chấp nhận, nhưng giữ nguyên tự nhiên hơn)."]},
];


registerRows("reported", RV);
GRAMMAR.theory["reported"] = { rows: RV, first: "r-backshift" };
})();
